name: nytroz_pos
description: Nytroz POS Flutter app.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  device_info_plus: ^11.3.0
  flutter_riverpod: ^2.5.1
  flutter_secure_storage: ^9.2.4
  go_router: ^14.2.7
  image_picker: ^1.1.2
  web: ^1.1.1
  mobile_scanner: 7.4.0
  crypto: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/pos_start_sale_background.png
    - assets/images/pos_home_start_new_sale.png
    - assets/images/pos_home_returns_exchanges.png
    - assets/images/pos_home_cash_drawer.png
    - assets/images/pos_home_resume_held_sales.png
    - assets/images/pos_home_online_orders.png
    - assets/images/pos_home_end_shift.png
    - assets/images/product_dummy.png
    - assets/images/logo.png
    - assets/images/log-screen-terminal.png
    - assets/images/login_brand_panel.png
