class TenantAdminPermissionAliases {
  const TenantAdminPermissionAliases._();

  static const Map<String, List<String>> _aliases = {
    'tenant_admin.dashboard.view': [
      'tenant_admin.dashboard.view',
      'dashboard.view',
      'tenant.dashboard.view',
    ],
    'dashboard.view': [
      'tenant_admin.dashboard.view',
      'dashboard.view',
      'tenant.dashboard.view',
    ],
    'tenant.dashboard.view': [
      'tenant_admin.dashboard.view',
      'dashboard.view',
      'tenant.dashboard.view',
    ],
    'dashboard.sales_summary.view': [
      'dashboard.sales_summary.view',
      'sales.summary.view',
      'dashboard.summary.view',
    ],
    'sales.summary.view': [
      'dashboard.sales_summary.view',
      'sales.summary.view',
      'dashboard.summary.view',
    ],
    'dashboard.summary.view': [
      'dashboard.sales_summary.view',
      'sales.summary.view',
      'dashboard.summary.view',
    ],
    'dashboard.orders_summary.view': [
      'dashboard.orders_summary.view',
      'sales.orders.view',
      'orders.view',
    ],
    'sales.orders.view': [
      'dashboard.orders_summary.view',
      'sales.orders.view',
      'orders.view',
    ],
    'orders.view': [
      'dashboard.orders_summary.view',
      'sales.orders.view',
      'orders.view',
    ],
    'dashboard.outlet_summary.view': [
      'dashboard.outlet_summary.view',
      'outlet.view',
      'outlets.view',
      'tenant.outlets.view',
      'tenant.outlets.manage',
    ],
    'outlet.view': [
      'dashboard.outlet_summary.view',
      'outlet.view',
      'outlets.view',
      'tenant.outlets.view',
      'tenant.outlets.manage',
    ],
    'outlets.view': [
      'dashboard.outlet_summary.view',
      'outlet.view',
      'outlets.view',
      'tenant.outlets.view',
      'tenant.outlets.manage',
    ],
    'tenant.outlets.view': [
      'tenant.outlets.view',
      'tenant.outlets.manage',
      'outlet.view',
      'outlets.view',
      'dashboard.outlet_summary.view',
    ],
    'dashboard.stock_alerts.view': [
      'dashboard.stock_alerts.view',
      'inventory.stock_alerts.view',
    ],
    'inventory.stock_alerts.view': [
      'dashboard.stock_alerts.view',
      'inventory.stock_alerts.view',
    ],
    'dashboard.till_status.view': [
      'dashboard.till_status.view',
      'tills.view',
      'tills.status.view',
      'tenant.tills.view',
    ],
    'till.view': [
      'dashboard.till_status.view',
      'till.view',
      'tills.view',
      'tenant.tills.view',
      'tenant.till.manage',
    ],
    'tills.view': [
      'dashboard.till_status.view',
      'till.view',
      'tills.view',
      'tenant.tills.view',
      'tenant.till.manage',
    ],
    'dashboard.sales_chart.view': [
      'dashboard.sales_chart.view',
      'analytics.sales.view',
      'analytics.sales_trend.view',
    ],
    'analytics.sales.view': [
      'dashboard.sales_chart.view',
      'analytics.sales.view',
      'analytics.sales_trend.view',
    ],
    'analytics.sales_trend.view': [
      'dashboard.sales_chart.view',
      'analytics.sales.view',
      'analytics.sales_trend.view',
    ],
    'dashboard.attention.view': [
      'dashboard.attention.view',
      'dashboard.alerts.view',
    ],
    'dashboard.alerts.view': [
      'dashboard.attention.view',
      'dashboard.alerts.view',
    ],
    'dashboard.attention.view_all': [
      'dashboard.attention.view_all',
      'dashboard.alerts.view',
    ],
    'outlet.create': [
      'outlet.create',
      'outlets.create',
      'tenant.outlets.manage',
    ],
    'outlets.create': [
      'outlet.create',
      'outlets.create',
      'tenant.outlets.manage',
    ],
    'outlet.summary.view': [
      'outlet.summary.view',
    ],
    'outlet.location_summary.view': [
      'outlet.location_summary.view',
      'outlet.summary.view',
    ],
    'outlet.filter.view': [
      'outlet.filter.view',
    ],
    'outlet.detail.view': [
      'outlet.detail.view',
      'tenant.outlets.details.view',
    ],
    'outlet.location.view': [
      'outlet.location.view',
    ],
    'outlet.status.view': [
      'outlet.status.view',
    ],
    'outlet.sales_summary.view': [
      'outlet.sales_summary.view',
    ],
    'outlet.till_summary.view': [
      'outlet.till_summary.view',
      'till.view',
      'tills.view',
      'tenant.tills.view',
    ],
    'outlet.staff_summary.view': [
      'outlet.staff_summary.view',
      'user.view',
      'users.view',
    ],
    'outlet.update': [
      'outlet.update',
      'outlets.update',
      'tenant.outlets.manage',
    ],
    'outlet.status.update': [
      'outlet.status.update',
      'tenant.outlets.manage',
    ],
    'outlet.delete': [
      'outlet.delete',
      'tenant.outlets.manage',
    ],
    'till.create': [
      'till.create',
      'tills.create',
      'tenant.tills.create',
      'tenant.till.manage',
    ],
    'tills.create': [
      'till.create',
      'tills.create',
      'tenant.tills.create',
      'tenant.till.manage',
    ],
    'till.update': [
      'till.update',
      'tills.update',
      'tenant.tills.update',
      'tenant.till.manage',
    ],
    'till.delete': [
      'till.delete',
      'tills.delete',
      'tenant.tills.delete',
      'tenant.till.manage',
    ],
    'till.status.view': [
      'till.status.view',
      'tills.status.view',
    ],
    'tills.status.view': [
      'till.status.view',
      'tills.status.view',
    ],
    'user.view': [
      'user.view',
      'users.view',
      'tenant.users.view',
      'tenant.users.manage',
      'tenant.user.manage',
    ],
    'users.view': [
      'user.view',
      'users.view',
      'tenant.users.view',
      'tenant.users.manage',
      'tenant.user.manage',
    ],
    'user.create': [
      'user.create',
      'users.create',
      'tenant.users.create',
    ],
    'users.create': [
      'user.create',
      'users.create',
      'tenant.users.create',
    ],
    'tenant.users.create': [
      'tenant.users.create',
      'user.create',
      'users.create',
    ],
    'user.invite.view': [
      'user.invite.view',
      'users.invites.view',
    ],
    'users.invites.view': [
      'user.invite.view',
      'users.invites.view',
    ],
    'user.invite.create': [
      'user.invite.create',
      'users.invite',
      'users.create',
      'tenant.users.invite',
    ],
    'users.invite': [
      'user.invite.create',
      'users.invite',
      'users.create',
      'tenant.users.invite',
    ],
    'tenant.users.invite': [
      'tenant.users.invite',
      'user.invite.create',
      'users.invite',
    ],
    'tenant.users.update': [
      'tenant.users.update',
      'user.update',
      'users.update',
    ],
    'user.update': [
      'tenant.users.update',
      'user.update',
      'users.update',
    ],
    'users.update': [
      'tenant.users.update',
      'user.update',
      'users.update',
    ],
    'tenant.users.delete': [
      'tenant.users.delete',
      'user.delete',
      'users.delete',
    ],
    'user.delete': [
      'tenant.users.delete',
      'user.delete',
      'users.delete',
    ],
    'users.delete': [
      'tenant.users.delete',
      'user.delete',
      'users.delete',
    ],
    'tenant.users.disable': [
      'tenant.users.disable',
      'user.disable',
      'users.disable',
    ],
    'user.disable': [
      'tenant.users.disable',
      'user.disable',
      'users.disable',
    ],
    'users.disable': [
      'tenant.users.disable',
      'user.disable',
      'users.disable',
    ],
    'tenant.users.details.view': [
      'tenant.users.details.view',
      'user.detail.view',
      'user.view',
      'users.view',
      'tenant.users.view',
    ],
    'user.detail.view': [
      'tenant.users.details.view',
      'user.detail.view',
      'user.view',
      'users.view',
      'tenant.users.view',
    ],
    'tenant.users.permission_override': [
      'tenant.users.permission_override',
      'user.permission_override',
      'users.permission_override',
    ],
    'user.permission_override': [
      'tenant.users.permission_override',
      'user.permission_override',
      'users.permission_override',
    ],
    'users.permission_override': [
      'tenant.users.permission_override',
      'user.permission_override',
      'users.permission_override',
    ],
    'role.view': [
      'role.view',
      'roles.view',
      'tenant.roles.view',
    ],
    'roles.view': [
      'role.view',
      'roles.view',
      'tenant.roles.view',
    ],
    'tenant.roles.view': [
      'tenant.roles.view',
      'role.view',
      'roles.view',
    ],
    'permission.view': [
      'permission.view',
      'permissions.view',
      'tenant.permissions.view',
    ],
    'permissions.view': [
      'permission.view',
      'permissions.view',
      'tenant.permissions.view',
    ],
    'tenant.permissions.view': [
      'tenant.permissions.view',
      'permission.view',
      'permissions.view',
    ],
    'roles.permissions.view': [
      'roles.permissions.view',
      'permission.view',
      'permissions.view',
    ],
    'roles.permissions.update': [
      'roles.permissions.update',
    ],
    'tenant.products.view': [
      'tenant.products.view',
      'product.view',
      'products.view',
      'catalog.product.view',
      'catalog.products.view',
    ],
    'product.view': [
      'product.view',
      'products.view',
      'catalog.product.view',
      'catalog.products.view',
      'tenant.products.view',
    ],
    'products.view': [
      'product.view',
      'products.view',
      'catalog.product.view',
      'catalog.products.view',
      'tenant.products.view',
    ],
    'catalog.product.view': [
      'product.view',
      'products.view',
      'catalog.product.view',
      'catalog.products.view',
      'tenant.products.view',
    ],
    'product.create': [
      'product.create',
      'products.create',
      'catalog.product.create',
      'catalog.products.create',
      'tenant.products.create',
    ],
    'products.create': [
      'product.create',
      'products.create',
      'catalog.product.create',
      'catalog.products.create',
      'tenant.products.create',
    ],
    'catalog.product.create': [
      'product.create',
      'products.create',
      'catalog.product.create',
      'catalog.products.create',
      'tenant.products.create',
    ],
    'tenant.products.create': [
      'tenant.products.create',
      'product.create',
      'products.create',
      'catalog.product.create',
      'catalog.products.create',
    ],
    'tenant.products.dashboard.view': [
      'tenant.products.dashboard.view',
    ],
    'tenant.categories.view': [
      'tenant.categories.view',
      'catalog.categories.view',
      'catalog.categories.manage',
      'category.view',
    ],
    'tenant.categories.create': [
      'tenant.categories.create',
      'catalog.categories.create',
      'catalog.categories.manage',
      'category.create',
    ],
    'tenant.categories.update': [
      'tenant.categories.update',
      'catalog.categories.update',
      'catalog.categories.manage',
      'category.update',
    ],
    'tenant.categories.delete': [
      'tenant.categories.delete',
      'catalog.categories.delete',
      'catalog.categories.manage',
      'category.delete',
    ],
    'tenant.brands.view': [
      'tenant.brands.view',
      'catalog.brands.view',
      'brand.view',
    ],
    'tenant.brands.create': [
      'tenant.brands.create',
      'catalog.brands.create',
      'catalog.brands.manage',
      'brand.create',
    ],
    'tenant.brands.update': [
      'tenant.brands.update',
      'catalog.brands.update',
      'catalog.brands.manage',
      'brand.update',
    ],
    'tenant.brands.delete': [
      'tenant.brands.delete',
      'catalog.brands.delete',
      'catalog.brands.manage',
      'brand.delete',
    ],
    'tenant.variant.templates.view': [
      'tenant.variant.templates.view',
      'catalog.variant.templates.view',
      'variant.templates.view',
    ],
    'catalog.product.update': [
      'product.create',
      'product.view',
      'catalog.product.update',
    ],
    'inventory.view': [
      'inventory.view',
      'inventory.stock.view',
    ],
    'inventory.alert.view': [
      'inventory.alert.view',
      'inventory.stock_alerts.view',
    ],
    'report.view': [
      'report.view',
      'reports.view',
      'reports.sales.view',
      'tenant.reports.sales.view',
    ],
    'reports.view': [
      'report.view',
      'reports.view',
      'reports.sales.view',
      'tenant.reports.sales.view',
    ],
    'report.sales.view': [
      'report.sales.view',
      'reports.sales.view',
      'dashboard.sales_summary.view',
      'sales.summary.view',
    ],
    'reports.sales.view': [
      'report.sales.view',
      'reports.sales.view',
      'dashboard.sales_summary.view',
      'sales.summary.view',
    ],
    'billing.view': [
      'billing.view',
      'tenant.billing.view',
    ],
    'tenant.billing.view': [
      'billing.view',
      'subscription.view',
      'subscription.billing.view',
      'tenant.billing.view',
    ],
    'subscription.view': [
      'billing.view',
      'subscription.view',
      'subscription.billing.view',
      'tenant.billing.view',
    ],
    'subscription.billing.view': [
      'billing.view',
      'subscription.view',
      'subscription.billing.view',
      'tenant.billing.view',
    ],
    'tenant_settings.view': [
      'tenant_settings.view',
      'settings.view',
      'tenant.settings.manage',
    ],
    'settings.view': [
      'tenant_settings.view',
      'settings.view',
      'tenant.settings.manage',
    ],
    'tenant.settings.manage': [
      'tenant.settings.manage',
    ],
    'activity_log.view': [
      'activity_log.view',
      'activity.view',
      'audit_logs.view',
      'tenant.activity.view',
    ],
    'activity.view': [
      'activity_log.view',
      'activity.view',
      'audit_logs.view',
      'tenant.activity.view',
    ],
    'audit_logs.view': [
      'activity_log.view',
      'activity.view',
      'audit_logs.view',
      'tenant.activity.view',
    ],
    'tenant.activity.view': [
      'activity_log.view',
      'activity.view',
      'audit_logs.view',
      'tenant.activity.view',
    ],
    'activity_log.detail.view': [
      'activity_log.detail.view',
    ],
    'pos.notifications.alerts.view': [
      'pos.notifications.alerts.view',
    ],
    'notification.read': [
      'notification.read',
    ],
    'tenant.online_store.view': [
      'tenant.online_store.view',
    ],
    'tenant.online_store.manage': [
      'tenant.online_store.manage',
    ],
    'tenant.online_store.publish': [
      'tenant.online_store.publish',
    ],
    'tenant.online_store.domains.manage': [
      'tenant.online_store.domains.manage',
    ],
    'tenant.online_store.branding.manage': [
      'tenant.online_store.branding.manage',
    ],
    'tenant.online_store.support.manage': [
      'tenant.online_store.support.manage',
    ],
    'tenant.online_store.fulfillment.manage': [
      'tenant.online_store.fulfillment.manage',
    ],
    'tenant.online_store.catalog.manage': [
      'tenant.online_store.catalog.manage',
    ],
    'tenant.online_store.policies.manage': [
      'tenant.online_store.policies.manage',
    ],
    'support.view': [
      'support.view',
    ],
    'tenant.till.manage': [
      'tills.view',
      'tills.create',
      'tills.status.view',
      'till.view',
      'till.create',
      'till.status.view',
      'tenant.till.manage',
      'tenant.tills.view',
      'tenant.tills.create',
      'tenant.tills.update',
      'tenant.tills.delete',
      'tenant.tills.manage',
    ],
    'tenant.user.manage': [
      'users.view',
      'users.create',
      'users.invite',
      'users.invites.view',
      'users.activity.view',
      'users.update',
      'users.delete',
      'users.disable',
      'users.permission_override',
      'user.view',
      'user.create',
      'user.invite.view',
      'user.invite.create',
      'user.update',
      'user.delete',
      'user.disable',
      'user.detail.view',
      'user.permission_override',
      'tenant.user.manage',
      'tenant.users.manage',
      'tenant.users.view',
      'tenant.users.create',
      'tenant.users.invite',
      'tenant.users.update',
      'tenant.users.delete',
      'tenant.users.disable',
      'tenant.users.details.view',
      'tenant.users.permission_override',
    ],
    'tenant.users.manage': [
      'users.view',
      'users.create',
      'users.invite',
      'users.invites.view',
      'users.activity.view',
      'users.update',
      'users.delete',
      'users.disable',
      'users.permission_override',
      'user.view',
      'user.create',
      'user.invite.view',
      'user.invite.create',
      'user.update',
      'user.delete',
      'user.disable',
      'user.detail.view',
      'user.permission_override',
      'tenant.user.manage',
      'tenant.users.manage',
      'tenant.users.view',
      'tenant.users.create',
      'tenant.users.invite',
      'tenant.users.update',
      'tenant.users.delete',
      'tenant.users.disable',
      'tenant.users.details.view',
      'tenant.users.permission_override',
    ],
    'tenant.role.manage': [
      'roles.view',
      'permissions.view',
      'role.view',
      'permission.view',
      'tenant.role.manage',
      'tenant.roles.manage',
    ],
    'tenant.roles.manage': [
      'roles.view',
      'permissions.view',
      'role.view',
      'permission.view',
      'tenant.role.manage',
      'tenant.roles.manage',
    ],
    'tenant.outlets.manage': [
      'tenant.outlets.manage',
      'tenant.outlets.view',
      'tenant.outlets.update',
      'outlet.view',
      'outlets.view',
      'outlet.create',
      'outlets.create',
      'outlet.update',
      'outlets.update',
      'outlet.delete',
      'outlet.status.update',
      'outlet.detail.view',
      'tenant.outlets.details.view',
      'tenant.outlets.revenue.view',
      'tenant.outlets.users.view',
      'tenant.outlets.tills.view',
      'dashboard.outlet_summary.view',
    ],
    'tenant.outlets.update': [
      'tenant.outlets.update',
      'tenant.outlets.manage',
      'outlet.update',
      'outlets.update',
    ],
    'tenant.outlets.details.view': [
      'tenant.outlets.details.view',
      'outlet.detail.view',
    ],
    'tenant.outlets.revenue.view': [
      'tenant.outlets.revenue.view',
      'tenant.reports.sales.view',
      'outlet.sales_summary.view',
      'report.sales.view',
    ],
    'tenant.outlets.users.view': [
      'tenant.outlets.users.view',
      'tenant.users.view',
      'user.view',
      'outlet.staff_summary.view',
    ],
    'tenant.outlets.tills.view': [
      'tenant.outlets.tills.view',
      'tenant.tills.view',
      'till.view',
      'outlet.till_summary.view',
    ],
    'tenant.users.view': [
      'tenant.users.view',
      'user.view',
      'users.view',
      'tenant.user.manage',
      'tenant.users.manage',
    ],
    'tenant.tills.view': [
      'tenant.tills.view',
      'till.view',
      'tills.view',
      'tenant.till.manage',
    ],
    'tenant.tills.create': [
      'tenant.tills.create',
      'till.create',
      'tills.create',
      'tenant.till.manage',
    ],
    'tenant.tills.update': [
      'tenant.tills.update',
      'till.update',
      'tenant.till.manage',
    ],
    'tenant.tills.delete': [
      'tenant.tills.delete',
      'till.delete',
      'tenant.till.manage',
    ],
    'tenant.hardware.view': [
      'tenant.hardware.view',
      'tenant.hardware.manage',
    ],
    'tenant.hardware.manage': [
      'tenant.hardware.manage',
    ],
    'tenant.reports.sales.view': [
      'tenant.reports.sales.view',
      'report.sales.view',
      'reports.sales.view',
      'tenant.outlets.revenue.view',
    ],
    'catalog.products.view': [
      'catalog.products.view',
      'product.view',
      'products.view',
      'catalog.product.view',
    ],
    'catalog.products.create': [
      'catalog.products.create',
      'product.create',
      'products.create',
      'catalog.product.create',
      'tenant.products.create',
    ],
    'catalog.products.update': [
      'catalog.products.update',
      'product.create',
      'product.view',
      'catalog.product.update',
    ],
    'inventory.stock.view': [
      'inventory.stock.view',
      'inventory.view',
      'tenant.stock.view',
      'tenant.stock.dashboard.view',
      'dashboard.stock_alerts.view',
      'inventory.stock_alerts.view',
    ],
    'tenant.stock.view': [
      'tenant.stock.view',
      'inventory.stock.view',
      'inventory.view',
      'tenant.stock.dashboard.view',
      'dashboard.stock_alerts.view',
      'inventory.stock_alerts.view',
    ],
    'tenant.stock.dashboard.view': [
      'tenant.stock.dashboard.view',
      'inventory.stock.view',
      'tenant.stock.view',
    ],
    'tenant.stock.in': [
      'tenant.stock.in',
      'inventory.receiving.manage',
    ],
    'inventory.receiving.manage': [
      'inventory.receiving.manage',
      'tenant.stock.in',
    ],
    'tenant.stock.opening': [
      'tenant.stock.opening',
      'inventory.opening_stock.manage',
      'inventory.opening_stock',
      'tenant.stock.in',
      'tenant.stock.view',
    ],
    'inventory.opening_stock.manage': [
      'inventory.opening_stock.manage',
      'tenant.stock.opening',
      'inventory.opening_stock',
      'tenant.stock.in',
    ],
    'inventory.serials.view': [
      'inventory.serials.view',
      'inventory.stock.view',
      'tenant.stock.view',
    ],
    'inventory.channel_allocation.view': [
      'inventory.channel_allocation.view',
      'inventory.channel_allocation.manage',
      'inventory.stock.view',
      'tenant.stock.view',
    ],
    'inventory.channel_allocation.manage': [
      'inventory.channel_allocation.manage',
    ],
    'inventory.stock.adjust': [
      'inventory.stock.adjust',
      'inventory.adjust',
      'tenant.stock.adjustments.view',
    ],
    'inventory.alerts.view': [
      'inventory.alerts.view',
      'inventory.alert.view',
      'inventory.stock_alerts.view',
      'dashboard.stock_alerts.view',
    ],
    'inventory.movements.view': [
      'inventory.movements.view',
      'tenant.stock.movements.view',
    ],
    'tenant.stock.out': [
      'tenant.stock.out',
    ],
    'tenant.stock.value.view': [
      'tenant.stock.value.view',
    ],
    'tenant.stock.movements.view': [
      'tenant.stock.movements.view',
    ],
    'tenant.stock.expiry.view': [
      'tenant.stock.expiry.view',
      'inventory.alert.view',
      'inventory.stock_alerts.view',
    ],
    'tenant.stock.adjustments.view': [
      'tenant.stock.adjustments.view',
      'inventory.adjust',
      'inventory.stock.adjust',
    ],
    'inventory.adjust': [
      'inventory.adjust',
      'inventory.stock.adjust',
      'tenant.stock.adjustments.view',
      'inventory.view',
    ],
    'tenant.stock.transfers.view': [
      'tenant.stock.transfers.view',
    ],
    'tenant.reports.products.view': [
      'tenant.reports.products.view',
      'report.view',
      'reports.view',
    ],
    'outlets.update': [
      'outlets.create',
      'outlets.view',
      'outlet.create',
      'outlet.view',
      'outlets.update',
      'outlet.update',
    ],
    'tenant.product.import': [
      'products.view',
      'products.create',
      'product.view',
      'product.create',
      'tenant.product.import',
    ],
    'catalog.collections.view': [
      'catalog.collections.view',
      'catalog.collections.manage',
    ],
    'catalog.collections.update': [
      'catalog.collections.update',
      'catalog.collections.manage',
    ],
    'catalog.collections.manage': [
      'catalog.collections.manage',
    ],
    'catalog.products.publish': [
      'catalog.products.publish',
    ],
    'catalog.product_media.manage': [
      'catalog.product_media.manage',
    ],
    'catalog.product_channels.manage': [
      'catalog.product_channels.manage',
    ],
    'catalog.variants.manage': [
      'catalog.variants.manage',
    ],
    'catalog.combo_components.manage': [
      'catalog.combo_components.manage',
    ],
    'catalog.barcodes.manage': [
      'catalog.barcodes.manage',
    ],
    'catalog.product_pricing.manage': [
      'catalog.product_pricing.manage',
    ],
    'catalog.product_cost.view': [
      'catalog.product_cost.view',
    ],
    'pricing.tax_classes.view': [
      'pricing.tax_classes.view',
      'tax.classes.view',
    ],
    'tax.classes.view': [
      'tax.classes.view',
      'pricing.tax_classes.view',
    ],
  };

  static Iterable<String> expand(String permissionCode) {
    final aliases = _aliases[permissionCode];
    if (aliases == null || aliases.isEmpty) {
      return [permissionCode];
    }

    return aliases;
  }
}
