import 'package:nytroz_pos/features/cart/domain/entities/pos_catalog_models.dart';
import 'package:nytroz_pos/features/cart/presentation/providers/pos_catalog_provider.dart';

const testPosCatalogState = PosNewSaleCatalogState(
  usedFallback: true,
  products: [
    PosCatalogProductSummary(
      productId: 'general-admission',
      name: 'General Admission',
      categoryName: 'Tickets',
      basePrice: 1500,
      hasVariants: false,
      stockLabel: '24 in stock',
    ),
    PosCatalogProductSummary(
      productId: 'vip-entry',
      name: 'VIP Entry',
      categoryName: 'Tickets',
      basePrice: 4500,
      hasVariants: false,
      stockLabel: '12 in stock',
    ),
    PosCatalogProductSummary(
      productId: 'guided-tour',
      name: 'Guided Tour',
      categoryName: 'Services',
      basePrice: 2000,
      hasVariants: false,
      stockLabel: 'Available',
    ),
    PosCatalogProductSummary(
      productId: 'event-t-shirt',
      name: 'Event T-Shirt',
      categoryName: 'Retail',
      basePrice: 2750,
      hasVariants: false,
      stockLabel: '18 in stock',
    ),
    PosCatalogProductSummary(
      productId: 'snack-combo',
      name: 'Snack Combo',
      categoryName: 'Food',
      basePrice: 950,
      hasVariants: false,
      stockLabel: '32 in stock',
    ),
    PosCatalogProductSummary(
      productId: 'annual-pass',
      name: 'Annual Pass',
      categoryName: 'Memberships',
      basePrice: 12000,
      hasVariants: false,
      stockLabel: 'Available',
    ),
    PosCatalogProductSummary(
      productId: 'family-pack',
      name: 'Family Pack',
      categoryName: 'Tickets',
      basePrice: 5200,
      hasVariants: false,
      stockLabel: '16 in stock',
    ),
    PosCatalogProductSummary(
      productId: 'photo-print',
      name: 'Photo Print',
      categoryName: 'Retail',
      basePrice: 1250,
      hasVariants: false,
      stockLabel: '40 in stock',
    ),
    PosCatalogProductSummary(
      productId: 'locker-rental',
      name: 'Locker Rental',
      categoryName: 'Services',
      basePrice: 700,
      hasVariants: false,
      stockLabel: 'Available',
    ),
    PosCatalogProductSummary(
      productId: 'coffee-voucher',
      name: 'Coffee Voucher',
      categoryName: 'Food',
      basePrice: 650,
      hasVariants: false,
      stockLabel: '50 in stock',
    ),
    PosCatalogProductSummary(
      productId: 'student-entry',
      name: 'Student Entry',
      categoryName: 'Tickets',
      basePrice: 900,
      hasVariants: false,
      stockLabel: '28 in stock',
    ),
    PosCatalogProductSummary(
      productId: 'premium-pass',
      name: 'Premium Pass',
      categoryName: 'Memberships',
      basePrice: 18000,
      hasVariants: false,
      stockLabel: 'Available',
    ),
  ],
);
