// Generated Chunk 2 Cashier POS canonical permission registry.
// Definitions only — no UI gating in Chunk 2.
class CashierPosCanonicalPermissionCodes {
  const CashierPosCanonicalPermissionCodes._();

  static const roleAssignableCodes = <String>[
    'pos.sales.dashboard.view',
    'pos.sales.new_sale.view',
    'pos.sales.new_sale.create',
    'pos.sales.catalog.view',
    'pos.sales.catalog.search',
    'pos.sales.cart.manage',
    'pos.sales.cart.add_item',
    'pos.sales.cart.update_item',
    'pos.sales.cart.remove_item',
    'pos.sales.cart.clear',
    'pos.sales.checkout.execute',
    'pos.sales.manual_discount.apply',
    'pos.sales.held_sales.create',
    'pos.sales.held_sales.view',
    'pos.sales.held_sales.recall',
    'pos.sales.order_history.view',
    'pos.payments.cash.accept',
    'pos.payments.card.accept',
    'pos.payments.qr.accept',
    'pos.payments.split.accept',
    'pos.receipts.digital.view',
    'pos.receipts.physical.print',
    'pos.receipts.history.reprint',
    'pos.orders.history.view',
    'pos.customers.management.view',
    'pos.customers.management.create',
    'pos.customers.management.update',
    'pos.returns.search_sale.view',
    'pos.returns.workflow.create',
    'pos.cash_drawer.position.view',
    'pos.cash_drawer.physical.manage',
    'pos.cash_drawer.movements.create',
    'pos.till.session.open',
    'pos.till.session.close',
    'pos.till.session.view',
    'pos.hardware.local_agent.settings',
    'pos.notifications.alerts.view',
    'commerce.online_order.orders.access',
    'commerce.online_order.orders.view',
    'commerce.online_order.fulfilment.start',
    'commerce.online_order.picking.view',
    'commerce.online_order.picking.pick',
    'commerce.online_order.picking.scan',
    'commerce.online_order.picking.manual_entry',
    'commerce.online_order.picking.report_issue',
    'commerce.online_order.picking.note',
    'commerce.online_order.packing.view',
    'commerce.online_order.packing.pack',
    'commerce.online_order.collection.mark_ready',
    'pos.shell.topbar.container',
    'pos.shell.topbar.brand',
    'pos.shell.topbar.session_status',
    'pos.shell.topbar.outlet',
    'pos.shell.topbar.till',
    'pos.shell.topbar.connectivity',
    'pos.shell.topbar.clock',
    'pos.shell.topbar.notification_bell',
    'pos.shell.bottom_nav.container',
    'pos.notifications.panel.view',
    'pos.notifications.panel.unread_count',
    'pos.notifications.messages.list',
    'pos.notifications.messages.title',
    'pos.notifications.messages.body',
    'pos.notifications.messages.timestamp',
    'pos.notifications.messages.open',
    'pos.notifications.messages.mark_read',
    'pos.notifications.messages.dismiss',
    'pos.notifications.messages.mark_all_read',
    'pos.home.profile.view',
    'pos.home.profile.avatar',
    'pos.home.profile.name',
    'pos.home.profile.role',
    'pos.home.session_summary.view',
    'pos.home.session_summary.total_sales',
    'pos.home.session_summary.transaction_count',
    'pos.home.session_summary.returns',
    'pos.home.session_summary.discounts',
    'pos.home.session_summary.net_sales',
    'pos.catalog.sections.quick_products',
    'pos.catalog.sections.popular',
    'pos.catalog.sections.frequently_sold',
    'pos.catalog.sections.offers',
    'pos.catalog.sections.sort',
    'pos.catalog.product_card.image',
    'pos.catalog.product_card.name',
    'pos.catalog.product_card.regular_price',
    'pos.catalog.product_card.sale_price',
    'pos.catalog.product_card.discount_badge',
    'pos.catalog.product_card.open_details',
    'pos.catalog.product_detail.view',
    'pos.catalog.product_detail.close',
    'pos.catalog.product_detail.image',
    'pos.catalog.product_detail.name',
    'pos.catalog.product_detail.price',
    'pos.catalog.product_detail.stock',
    'pos.catalog.product_detail.sku',
    'pos.catalog.product_detail.description',
    'pos.catalog.product_detail.variants',
    'pos.catalog.product_detail.variant_select',
    'pos.catalog.product_detail.available_qty',
    'pos.catalog.product_detail.quantity_display',
    'pos.catalog.product_detail.note_view',
    'pos.catalog.product_detail.note_entry',
    'pos.catalog.product_detail.recommendations',
    'pos.catalog.product_detail.cancel',
    'pos.held_sales.popup.view',
    'pos.held_sales.popup.reference',
    'pos.held_sales.popup.note',
    'pos.held_sales.popup.expiry',
    'pos.held_sales.list.filters',
    'pos.held_sales.list.active_count',
    'pos.held_sales.list.customer',
    'pos.held_sales.list.value',
    'pos.held_sales.list.item_count',
    'pos.held_sales.list.parked_time',
    'pos.held_sales.list.expiry_time',
    'pos.held_sales.list.items',
    'pos.held_sales.list.pagination',
    'pos.held_sales.list.summary',
    'pos.sales.held_sales.cancel',
    'pos.cart.summary.view',
    'pos.cart.summary.item_count',
    'pos.cart.summary.subtotal',
    'pos.cart.summary.discount',
    'pos.cart.summary.tax',
    'pos.cart.summary.total',
    'pos.cart.lines.list',
    'pos.cart.lines.name',
    'pos.cart.lines.quantity',
    'pos.cart.lines.unit_price',
    'pos.cart.lines.line_total',
    'pos.cart.lines.note',
    'pos.cart.lines.image',
    'pos.catalog.search.bar',
    'pos.catalog.search.clear',
    'pos.catalog.search.results',
    'pos.catalog.search.empty_state',
    'pos.catalog.search.scanner_hint',
    'pos.checkout.methods.cash_tile',
    'pos.checkout.methods.card_tile',
    'pos.checkout.methods.qr_tile',
    'pos.checkout.methods.split_tile',
    'pos.checkout.methods.container',
    'pos.discount.panel.view',
    'pos.discount.panel.amount_entry',
    'pos.discount.panel.reason_entry',
    'pos.discount.panel.apply_action',
    'pos.discount.panel.cancel_action',
    'pos.new_sale.chrome.header',
    'pos.new_sale.chrome.park_action',
    'pos.new_sale.chrome.customer_chip',
    'pos.new_sale.chrome.empty_cart',
    'pos.new_sale.chrome.checkout_action',
    'pos.new_sale.chrome.held_count',
    'pos.new_sale.chrome.clear_cart_action',
    'pos.checkout.summary.payment',
    'pos.checkout.summary.items',
    'pos.checkout.summary.quantity',
    'pos.checkout.summary.price',
    'pos.checkout.summary.line_total',
    'pos.checkout.customer.summary',
    'pos.checkout.summary.subtotal',
    'pos.checkout.summary.discount',
    'pos.checkout.summary.tax',
    'pos.checkout.summary.total',
    'pos.cash_payment.summary.order',
    'pos.cash_payment.line.item',
    'pos.cash_payment.line.quantity',
    'pos.cash_payment.line.price',
    'pos.cash_payment.line.item_total',
    'pos.cash_payment.summary.subtotal',
    'pos.cash_payment.summary.discount',
    'pos.cash_payment.summary.tax',
    'pos.cash_payment.summary.total_due',
    'pos.cash_payment.tender.amount_received_view',
    'pos.cash_payment.tender.amount_received_entry',
    'pos.cash_payment.tender.due_amount',
    'pos.cash_payment.tender.exact',
    'pos.cash_payment.quick_amounts.container',
    'pos.cash_payment.quick_amounts.slot_1',
    'pos.cash_payment.quick_amounts.slot_2',
    'pos.cash_payment.quick_amounts.slot_3',
    'pos.cash_payment.numpad.container',
    'pos.cash_payment.numpad.digit_0',
    'pos.cash_payment.numpad.digit_1',
    'pos.cash_payment.numpad.digit_2',
    'pos.cash_payment.numpad.digit_3',
    'pos.cash_payment.numpad.digit_4',
    'pos.cash_payment.numpad.digit_5',
    'pos.cash_payment.numpad.digit_6',
    'pos.cash_payment.numpad.digit_7',
    'pos.cash_payment.numpad.digit_8',
    'pos.cash_payment.numpad.digit_9',
    'pos.cash_payment.numpad.digit_00',
    'pos.cash_payment.numpad.decimal',
    'pos.cash_payment.controls.backspace',
    'pos.cash_payment.controls.clear',
    'pos.cash_payment.tender.change_due',
    'pos.cash_payment.completion.execute',
    'pos.sale_complete.message.success',
    'pos.sale_complete.details.receipt_number',
    'pos.sale_complete.details.payment_method',
    'pos.sale_complete.details.datetime',
    'pos.sale_complete.details.cashier',
    'pos.sale_complete.details.customer',
    'pos.sale_complete.details.cash_received',
    'pos.sale_complete.details.change_due',
    'pos.sale_complete.details.total_paid',
    'pos.receipts.details.store',
    'pos.receipts.details.receipt_number',
    'pos.receipts.details.datetime',
    'pos.receipts.details.cashier',
    'pos.receipts.details.customer',
    'pos.receipts.details.terminal',
    'pos.receipts.details.payment_method',
    'pos.receipts.details.items',
    'pos.receipts.details.item_quantity',
    'pos.receipts.details.item_value',
    'pos.receipts.details.item_rate',
    'pos.receipts.details.subtotal',
    'pos.receipts.details.discount',
    'pos.receipts.details.total',
    'pos.receipts.details.paid_amount',
    'pos.receipts.details.change_due',
    'pos.customers.list.search',
    'pos.customers.list.filters',
    'pos.customers.list.id',
    'pos.customers.list.name',
    'pos.customers.list.phone',
    'pos.customers.list.email',
    'pos.customers.list.source',
    'pos.customers.list.status',
    'pos.customers.list.order_count',
    'pos.customers.list.total_spend',
    'pos.customers.list.pagination',
    'pos.customers.details.joined_date',
    'pos.customers.details.average_order_value',
    'pos.customers.history.recent_purchases',
    'pos.customers.history.purchase_amounts',
    'pos.customers.history.purchase_history',
    'pos.cash_drawer.summary.till',
    'pos.cash_drawer.summary.status',
    'pos.cash_drawer.summary.opening_cash',
    'pos.cash_drawer.summary.cash_sales',
    'pos.cash_drawer.summary.expected_cash',
    'pos.cash_drawer.movements.list',
    'pos.cash_drawer.movements.type',
    'pos.cash_drawer.movements.date',
    'pos.cash_drawer.movements.time',
    'pos.cash_drawer.movements.cashier',
    'pos.cash_drawer.movements.amount_view',
    'pos.cash_drawer.open_popup.view',
    'pos.cash_drawer.open_popup.cancel',
    'pos.cash_drawer.open_popup.continue',
    'pos.till.opening.starting_cash_view',
    'pos.till.opening.starting_cash_entry',
    'pos.till.opening.validation_message',
    'pos.till.opening.note_view',
    'pos.till.opening.note_entry',
    'pos.till.opening.quick_amounts',
    'pos.till.opening.quick_slot_1',
    'pos.till.opening.quick_slot_2',
    'pos.till.opening.quick_slot_3',
    'pos.till.opening.numpad',
    'pos.till.opening.backspace',
    'pos.till.opening.clear',
    'pos.till.opening.confirm_message',
    'pos.till.opening.key_0',
    'pos.till.opening.key_1',
    'pos.till.opening.key_2',
    'pos.till.opening.key_3',
    'pos.till.opening.key_4',
    'pos.till.opening.key_5',
    'pos.till.opening.key_6',
    'pos.till.opening.key_7',
    'pos.till.opening.key_8',
    'pos.till.opening.key_9',
    'pos.till.opening.key_00',
    'pos.till.opening.key_decimal',
    'pos.till.closing.back',
    'pos.till.closing.till',
    'pos.till.closing.opened_by',
    'pos.till.closing.opened_time',
    'pos.till.closing.expected_cash',
    'pos.till.closing.counted_cash_entry',
    'pos.till.closing.difference',
    'pos.till.closing.balance_status',
    'pos.till.closing.mismatch_reason',
    'pos.till.closing.notes',
    'pos.till.closing.summary',
    'pos.till.closing.expected_cash_summary',
    'pos.till.closing.counted_cash_summary',
    'pos.till.closing.difference_summary',
    'pos.till.closing.status_summary',
    'pos.shell.navigation.settings',
    'pos.customers.management.attach_sale',
    'pos.customers.management.deactivate',
    'pos.cash_drawer.movements.cash_in',
    'pos.cash_drawer.movements.cash_out',
    'pos.cash_drawer.movements.cash_drop',
    'pos.cash_drawer.open_reason.provide_change',
    'pos.cash_drawer.open_reason.till_check',
    'pos.cash_drawer.open_reason.cash_count',
    'pos.cash_drawer.open_reason.manager_operation',
    'pos.cash_drawer.open_reason.other',
    'pos.shell.navigation.offline_banner',
    'pos.home.actions.online_orders_entry',
    'pos.home.actions.returns_entry',
    'pos.cash_movements.cash_in.till',
    'pos.cash_movements.cash_in.expected_cash',
    'pos.cash_movements.cash_in.available_cash',
    'pos.cash_movements.cash_in.amount_entry',
    'pos.cash_movements.cash_in.reason',
    'pos.cash_movements.cash_in.note',
    'pos.cash_movements.cash_in.manager_pin',
    'pos.cash_movements.cash_in.summary',
    'pos.cash_movements.cash_in.resulting_balance',
    'pos.cash_movements.cash_in.validation_message',
    'pos.cash_movements.cash_in.confirm',
    'pos.cash_movements.cash_in.cancel',
    'pos.cash_movements.cash_out.till',
    'pos.cash_movements.cash_out.expected_cash',
    'pos.cash_movements.cash_out.available_cash',
    'pos.cash_movements.cash_out.amount_entry',
    'pos.cash_movements.cash_out.reason',
    'pos.cash_movements.cash_out.note',
    'pos.cash_movements.cash_out.manager_pin',
    'pos.cash_movements.cash_out.summary',
    'pos.cash_movements.cash_out.resulting_balance',
    'pos.cash_movements.cash_out.validation_message',
    'pos.cash_movements.cash_out.confirm',
    'pos.cash_movements.cash_out.cancel',
    'pos.cash_movements.cash_drop.till',
    'pos.cash_movements.cash_drop.expected_cash',
    'pos.cash_movements.cash_drop.available_cash',
    'pos.cash_movements.cash_drop.amount_entry',
    'pos.cash_movements.cash_drop.reason',
    'pos.cash_movements.cash_drop.note',
    'pos.cash_movements.cash_drop.manager_pin',
    'pos.cash_movements.cash_drop.summary',
    'pos.cash_movements.cash_drop.resulting_balance',
    'pos.cash_movements.cash_drop.validation_message',
    'pos.cash_movements.cash_drop.confirm',
    'pos.cash_movements.cash_drop.cancel',
  ];

  static const preAuthCodes = <String>[
    'pre_auth.login.screen.view',
    'pre_auth.login.branding.view',
    'pre_auth.login.email.input',
    'pre_auth.login.password.input',
    'pre_auth.login.password_visibility.toggle',
    'pre_auth.login.submit.execute',
    'pre_auth.login.validation.message',
  ];

  static const sensitiveCodes = <String>[
    'pos.home.session_summary.total_sales',
    'pos.home.session_summary.discounts',
    'pos.home.session_summary.net_sales',
    'pos.held_sales.list.value',
    'pos.held_sales.list.summary',
    'pos.cart.summary.discount',
    'pos.cart.summary.total',
    'pos.discount.panel.amount_entry',
    'pos.checkout.summary.discount',
    'pos.checkout.summary.total',
    'pos.cash_payment.summary.discount',
    'pos.cash_payment.summary.total_due',
    'pos.cash_payment.tender.amount_received_view',
    'pos.cash_payment.tender.amount_received_entry',
    'pos.cash_payment.tender.due_amount',
    'pos.cash_payment.tender.change_due',
    'pos.sale_complete.details.customer',
    'pos.sale_complete.details.cash_received',
    'pos.sale_complete.details.change_due',
    'pos.sale_complete.details.total_paid',
    'pos.receipts.details.customer',
    'pos.receipts.details.payment_method',
    'pos.receipts.details.discount',
    'pos.receipts.details.total',
    'pos.receipts.details.paid_amount',
    'pos.receipts.details.change_due',
    'pos.customers.list.phone',
    'pos.customers.list.email',
    'pos.customers.list.total_spend',
    'pos.customers.details.average_order_value',
    'pos.customers.history.recent_purchases',
    'pos.customers.history.purchase_amounts',
    'pos.customers.history.purchase_history',
    'pos.cash_drawer.summary.opening_cash',
    'pos.cash_drawer.summary.cash_sales',
    'pos.cash_drawer.summary.expected_cash',
    'pos.cash_drawer.movements.amount_view',
    'pos.till.opening.starting_cash_view',
    'pos.till.opening.starting_cash_entry',
    'pos.till.closing.expected_cash',
    'pos.till.closing.counted_cash_entry',
    'pos.till.closing.difference',
    'pos.till.closing.expected_cash_summary',
    'pos.till.closing.counted_cash_summary',
    'pos.till.closing.difference_summary',
    'pos.cash_movements.cash_in.expected_cash',
    'pos.cash_movements.cash_in.available_cash',
    'pos.cash_movements.cash_in.amount_entry',
    'pos.cash_movements.cash_in.manager_pin',
    'pos.cash_movements.cash_in.resulting_balance',
    'pos.cash_movements.cash_out.expected_cash',
    'pos.cash_movements.cash_out.available_cash',
    'pos.cash_movements.cash_out.amount_entry',
    'pos.cash_movements.cash_out.manager_pin',
    'pos.cash_movements.cash_out.resulting_balance',
    'pos.cash_movements.cash_drop.expected_cash',
    'pos.cash_movements.cash_drop.available_cash',
    'pos.cash_movements.cash_drop.amount_entry',
    'pos.cash_movements.cash_drop.manager_pin',
    'pos.cash_movements.cash_drop.resulting_balance',
  ];

  static const parentByChild = <String, String>{
    'pos.shell.topbar.container': 'pos.sales.dashboard.view',
    'pos.shell.topbar.brand': 'pos.sales.dashboard.view',
    'pos.shell.topbar.session_status': 'pos.sales.dashboard.view',
    'pos.shell.topbar.outlet': 'pos.sales.dashboard.view',
    'pos.shell.topbar.till': 'pos.sales.dashboard.view',
    'pos.shell.topbar.connectivity': 'pos.sales.dashboard.view',
    'pos.shell.topbar.clock': 'pos.sales.dashboard.view',
    'pos.shell.topbar.notification_bell': 'pos.sales.dashboard.view',
    'pos.shell.bottom_nav.container': 'pos.sales.dashboard.view',
    'pos.notifications.panel.view': 'pos.notifications.alerts.view',
    'pos.notifications.panel.unread_count': 'pos.notifications.alerts.view',
    'pos.notifications.messages.list': 'pos.notifications.alerts.view',
    'pos.notifications.messages.title': 'pos.notifications.alerts.view',
    'pos.notifications.messages.body': 'pos.notifications.alerts.view',
    'pos.notifications.messages.timestamp': 'pos.notifications.alerts.view',
    'pos.notifications.messages.open': 'pos.notifications.alerts.view',
    'pos.notifications.messages.mark_read': 'pos.notifications.alerts.view',
    'pos.notifications.messages.dismiss': 'pos.notifications.alerts.view',
    'pos.notifications.messages.mark_all_read': 'pos.notifications.alerts.view',
    'pos.home.profile.view': 'pos.sales.dashboard.view',
    'pos.home.profile.avatar': 'pos.sales.dashboard.view',
    'pos.home.profile.name': 'pos.sales.dashboard.view',
    'pos.home.profile.role': 'pos.sales.dashboard.view',
    'pos.home.session_summary.view': 'pos.sales.dashboard.view',
    'pos.home.session_summary.total_sales': 'pos.sales.dashboard.view',
    'pos.home.session_summary.transaction_count': 'pos.sales.dashboard.view',
    'pos.home.session_summary.returns': 'pos.sales.dashboard.view',
    'pos.home.session_summary.discounts': 'pos.sales.dashboard.view',
    'pos.home.session_summary.net_sales': 'pos.sales.dashboard.view',
    'pos.catalog.sections.quick_products': 'pos.sales.catalog.view',
    'pos.catalog.sections.popular': 'pos.sales.catalog.view',
    'pos.catalog.sections.frequently_sold': 'pos.sales.catalog.view',
    'pos.catalog.sections.offers': 'pos.sales.catalog.view',
    'pos.catalog.sections.sort': 'pos.sales.catalog.view',
    'pos.catalog.product_card.image': 'pos.sales.catalog.view',
    'pos.catalog.product_card.name': 'pos.sales.catalog.view',
    'pos.catalog.product_card.regular_price': 'pos.sales.catalog.view',
    'pos.catalog.product_card.sale_price': 'pos.sales.catalog.view',
    'pos.catalog.product_card.discount_badge': 'pos.sales.catalog.view',
    'pos.catalog.product_card.open_details': 'pos.sales.catalog.view',
    'pos.catalog.product_detail.view': 'pos.sales.catalog.view',
    'pos.catalog.product_detail.close': 'pos.sales.catalog.view',
    'pos.catalog.product_detail.image': 'pos.sales.catalog.view',
    'pos.catalog.product_detail.name': 'pos.sales.catalog.view',
    'pos.catalog.product_detail.price': 'pos.sales.catalog.view',
    'pos.catalog.product_detail.stock': 'pos.sales.catalog.view',
    'pos.catalog.product_detail.sku': 'pos.sales.catalog.view',
    'pos.catalog.product_detail.description': 'pos.sales.catalog.view',
    'pos.catalog.product_detail.variants': 'pos.sales.catalog.view',
    'pos.catalog.product_detail.variant_select': 'pos.sales.catalog.view',
    'pos.catalog.product_detail.available_qty': 'pos.sales.catalog.view',
    'pos.catalog.product_detail.quantity_display': 'pos.sales.catalog.view',
    'pos.catalog.product_detail.note_view': 'pos.sales.catalog.view',
    'pos.catalog.product_detail.note_entry': 'pos.sales.catalog.view',
    'pos.catalog.product_detail.recommendations': 'pos.sales.catalog.view',
    'pos.catalog.product_detail.cancel': 'pos.sales.catalog.view',
    'pos.held_sales.popup.view': 'pos.sales.held_sales.create',
    'pos.held_sales.popup.reference': 'pos.sales.held_sales.create',
    'pos.held_sales.popup.note': 'pos.sales.held_sales.create',
    'pos.held_sales.popup.expiry': 'pos.sales.held_sales.create',
    'pos.held_sales.list.filters': 'pos.sales.held_sales.view',
    'pos.held_sales.list.active_count': 'pos.sales.held_sales.view',
    'pos.held_sales.list.customer': 'pos.sales.held_sales.view',
    'pos.held_sales.list.value': 'pos.sales.held_sales.view',
    'pos.held_sales.list.item_count': 'pos.sales.held_sales.view',
    'pos.held_sales.list.parked_time': 'pos.sales.held_sales.view',
    'pos.held_sales.list.expiry_time': 'pos.sales.held_sales.view',
    'pos.held_sales.list.items': 'pos.sales.held_sales.view',
    'pos.held_sales.list.pagination': 'pos.sales.held_sales.view',
    'pos.held_sales.list.summary': 'pos.sales.held_sales.view',
    'pos.sales.held_sales.cancel': 'pos.sales.held_sales.create',
    'pos.cart.summary.view': 'pos.sales.cart.manage',
    'pos.cart.summary.item_count': 'pos.sales.cart.manage',
    'pos.cart.summary.subtotal': 'pos.sales.cart.manage',
    'pos.cart.summary.discount': 'pos.sales.cart.manage',
    'pos.cart.summary.tax': 'pos.sales.cart.manage',
    'pos.cart.summary.total': 'pos.sales.cart.manage',
    'pos.cart.lines.list': 'pos.sales.cart.manage',
    'pos.cart.lines.name': 'pos.sales.cart.manage',
    'pos.cart.lines.quantity': 'pos.sales.cart.manage',
    'pos.cart.lines.unit_price': 'pos.sales.cart.manage',
    'pos.cart.lines.line_total': 'pos.sales.cart.manage',
    'pos.cart.lines.note': 'pos.sales.cart.manage',
    'pos.cart.lines.image': 'pos.sales.cart.manage',
    'pos.catalog.search.bar': 'pos.sales.catalog.search',
    'pos.catalog.search.clear': 'pos.sales.catalog.search',
    'pos.catalog.search.results': 'pos.sales.catalog.search',
    'pos.catalog.search.empty_state': 'pos.sales.catalog.search',
    'pos.catalog.search.scanner_hint': 'pos.sales.catalog.search',
    'pos.checkout.methods.cash_tile': 'pos.payments.cash.accept',
    'pos.checkout.methods.card_tile': 'pos.payments.card.accept',
    'pos.checkout.methods.qr_tile': 'pos.payments.qr.accept',
    'pos.checkout.methods.split_tile': 'pos.payments.split.accept',
    'pos.checkout.methods.container': 'pos.sales.checkout.execute',
    'pos.discount.panel.view': 'pos.sales.manual_discount.apply',
    'pos.discount.panel.amount_entry': 'pos.sales.manual_discount.apply',
    'pos.discount.panel.reason_entry': 'pos.sales.manual_discount.apply',
    'pos.discount.panel.apply_action': 'pos.sales.manual_discount.apply',
    'pos.discount.panel.cancel_action': 'pos.sales.manual_discount.apply',
    'pos.new_sale.chrome.header': 'pos.sales.new_sale.view',
    'pos.new_sale.chrome.park_action': 'pos.sales.new_sale.view',
    'pos.new_sale.chrome.customer_chip': 'pos.sales.new_sale.view',
    'pos.new_sale.chrome.empty_cart': 'pos.sales.new_sale.view',
    'pos.new_sale.chrome.checkout_action': 'pos.sales.new_sale.view',
    'pos.new_sale.chrome.held_count': 'pos.sales.new_sale.view',
    'pos.new_sale.chrome.clear_cart_action': 'pos.sales.new_sale.view',
    'pos.checkout.summary.payment': 'pos.sales.checkout.execute',
    'pos.checkout.summary.items': 'pos.sales.checkout.execute',
    'pos.checkout.summary.quantity': 'pos.sales.checkout.execute',
    'pos.checkout.summary.price': 'pos.sales.checkout.execute',
    'pos.checkout.summary.line_total': 'pos.sales.checkout.execute',
    'pos.checkout.customer.summary': 'pos.sales.checkout.execute',
    'pos.checkout.summary.subtotal': 'pos.sales.checkout.execute',
    'pos.checkout.summary.discount': 'pos.sales.checkout.execute',
    'pos.checkout.summary.tax': 'pos.sales.checkout.execute',
    'pos.checkout.summary.total': 'pos.sales.checkout.execute',
    'pos.cash_payment.summary.order': 'pos.payments.cash.accept',
    'pos.cash_payment.line.item': 'pos.payments.cash.accept',
    'pos.cash_payment.line.quantity': 'pos.payments.cash.accept',
    'pos.cash_payment.line.price': 'pos.payments.cash.accept',
    'pos.cash_payment.line.item_total': 'pos.payments.cash.accept',
    'pos.cash_payment.summary.subtotal': 'pos.payments.cash.accept',
    'pos.cash_payment.summary.discount': 'pos.payments.cash.accept',
    'pos.cash_payment.summary.tax': 'pos.payments.cash.accept',
    'pos.cash_payment.summary.total_due': 'pos.payments.cash.accept',
    'pos.cash_payment.tender.amount_received_view': 'pos.payments.cash.accept',
    'pos.cash_payment.tender.amount_received_entry': 'pos.payments.cash.accept',
    'pos.cash_payment.tender.due_amount': 'pos.payments.cash.accept',
    'pos.cash_payment.tender.exact': 'pos.payments.cash.accept',
    'pos.cash_payment.quick_amounts.container': 'pos.payments.cash.accept',
    'pos.cash_payment.quick_amounts.slot_1': 'pos.payments.cash.accept',
    'pos.cash_payment.quick_amounts.slot_2': 'pos.payments.cash.accept',
    'pos.cash_payment.quick_amounts.slot_3': 'pos.payments.cash.accept',
    'pos.cash_payment.numpad.container': 'pos.payments.cash.accept',
    'pos.cash_payment.numpad.digit_0': 'pos.payments.cash.accept',
    'pos.cash_payment.numpad.digit_1': 'pos.payments.cash.accept',
    'pos.cash_payment.numpad.digit_2': 'pos.payments.cash.accept',
    'pos.cash_payment.numpad.digit_3': 'pos.payments.cash.accept',
    'pos.cash_payment.numpad.digit_4': 'pos.payments.cash.accept',
    'pos.cash_payment.numpad.digit_5': 'pos.payments.cash.accept',
    'pos.cash_payment.numpad.digit_6': 'pos.payments.cash.accept',
    'pos.cash_payment.numpad.digit_7': 'pos.payments.cash.accept',
    'pos.cash_payment.numpad.digit_8': 'pos.payments.cash.accept',
    'pos.cash_payment.numpad.digit_9': 'pos.payments.cash.accept',
    'pos.cash_payment.numpad.digit_00': 'pos.payments.cash.accept',
    'pos.cash_payment.numpad.decimal': 'pos.payments.cash.accept',
    'pos.cash_payment.controls.backspace': 'pos.payments.cash.accept',
    'pos.cash_payment.controls.clear': 'pos.payments.cash.accept',
    'pos.cash_payment.tender.change_due': 'pos.payments.cash.accept',
    'pos.cash_payment.completion.execute': 'pos.payments.cash.accept',
    'pos.sale_complete.message.success': 'pos.receipts.digital.view',
    'pos.sale_complete.details.receipt_number': 'pos.receipts.digital.view',
    'pos.sale_complete.details.payment_method': 'pos.receipts.digital.view',
    'pos.sale_complete.details.datetime': 'pos.receipts.digital.view',
    'pos.sale_complete.details.cashier': 'pos.receipts.digital.view',
    'pos.sale_complete.details.customer': 'pos.receipts.digital.view',
    'pos.sale_complete.details.cash_received': 'pos.receipts.digital.view',
    'pos.sale_complete.details.change_due': 'pos.receipts.digital.view',
    'pos.sale_complete.details.total_paid': 'pos.receipts.digital.view',
    'pos.receipts.details.store': 'pos.receipts.digital.view',
    'pos.receipts.details.receipt_number': 'pos.receipts.digital.view',
    'pos.receipts.details.datetime': 'pos.receipts.digital.view',
    'pos.receipts.details.cashier': 'pos.receipts.digital.view',
    'pos.receipts.details.customer': 'pos.receipts.digital.view',
    'pos.receipts.details.terminal': 'pos.receipts.digital.view',
    'pos.receipts.details.payment_method': 'pos.receipts.digital.view',
    'pos.receipts.details.items': 'pos.receipts.digital.view',
    'pos.receipts.details.item_quantity': 'pos.receipts.digital.view',
    'pos.receipts.details.item_value': 'pos.receipts.digital.view',
    'pos.receipts.details.item_rate': 'pos.receipts.digital.view',
    'pos.receipts.details.subtotal': 'pos.receipts.digital.view',
    'pos.receipts.details.discount': 'pos.receipts.digital.view',
    'pos.receipts.details.total': 'pos.receipts.digital.view',
    'pos.receipts.details.paid_amount': 'pos.receipts.digital.view',
    'pos.receipts.details.change_due': 'pos.receipts.digital.view',
    'pos.customers.list.search': 'pos.customers.management.view',
    'pos.customers.list.filters': 'pos.customers.management.view',
    'pos.customers.list.id': 'pos.customers.management.view',
    'pos.customers.list.name': 'pos.customers.management.view',
    'pos.customers.list.phone': 'pos.customers.management.view',
    'pos.customers.list.email': 'pos.customers.management.view',
    'pos.customers.list.source': 'pos.customers.management.view',
    'pos.customers.list.status': 'pos.customers.management.view',
    'pos.customers.list.order_count': 'pos.customers.management.view',
    'pos.customers.list.total_spend': 'pos.customers.management.view',
    'pos.customers.list.pagination': 'pos.customers.management.view',
    'pos.customers.details.joined_date': 'pos.customers.management.view',
    'pos.customers.details.average_order_value': 'pos.customers.management.view',
    'pos.customers.history.recent_purchases': 'pos.customers.management.view',
    'pos.customers.history.purchase_amounts': 'pos.customers.management.view',
    'pos.customers.history.purchase_history': 'pos.customers.management.view',
    'pos.cash_drawer.summary.till': 'pos.cash_drawer.position.view',
    'pos.cash_drawer.summary.status': 'pos.cash_drawer.position.view',
    'pos.cash_drawer.summary.opening_cash': 'pos.cash_drawer.position.view',
    'pos.cash_drawer.summary.cash_sales': 'pos.cash_drawer.position.view',
    'pos.cash_drawer.summary.expected_cash': 'pos.cash_drawer.position.view',
    'pos.cash_drawer.movements.list': 'pos.cash_drawer.position.view',
    'pos.cash_drawer.movements.type': 'pos.cash_drawer.position.view',
    'pos.cash_drawer.movements.date': 'pos.cash_drawer.position.view',
    'pos.cash_drawer.movements.time': 'pos.cash_drawer.position.view',
    'pos.cash_drawer.movements.cashier': 'pos.cash_drawer.position.view',
    'pos.cash_drawer.movements.amount_view': 'pos.cash_drawer.position.view',
    'pos.cash_drawer.open_popup.view': 'pos.cash_drawer.physical.manage',
    'pos.cash_drawer.open_popup.cancel': 'pos.cash_drawer.physical.manage',
    'pos.cash_drawer.open_popup.continue': 'pos.cash_drawer.physical.manage',
    'pos.till.opening.starting_cash_view': 'pos.till.session.open',
    'pos.till.opening.starting_cash_entry': 'pos.till.session.open',
    'pos.till.opening.validation_message': 'pos.till.session.open',
    'pos.till.opening.note_view': 'pos.till.session.open',
    'pos.till.opening.note_entry': 'pos.till.session.open',
    'pos.till.opening.quick_amounts': 'pos.till.session.open',
    'pos.till.opening.quick_slot_1': 'pos.till.session.open',
    'pos.till.opening.quick_slot_2': 'pos.till.session.open',
    'pos.till.opening.quick_slot_3': 'pos.till.session.open',
    'pos.till.opening.numpad': 'pos.till.session.open',
    'pos.till.opening.backspace': 'pos.till.session.open',
    'pos.till.opening.clear': 'pos.till.session.open',
    'pos.till.opening.confirm_message': 'pos.till.session.open',
    'pos.till.opening.key_0': 'pos.till.session.open',
    'pos.till.opening.key_1': 'pos.till.session.open',
    'pos.till.opening.key_2': 'pos.till.session.open',
    'pos.till.opening.key_3': 'pos.till.session.open',
    'pos.till.opening.key_4': 'pos.till.session.open',
    'pos.till.opening.key_5': 'pos.till.session.open',
    'pos.till.opening.key_6': 'pos.till.session.open',
    'pos.till.opening.key_7': 'pos.till.session.open',
    'pos.till.opening.key_8': 'pos.till.session.open',
    'pos.till.opening.key_9': 'pos.till.session.open',
    'pos.till.opening.key_00': 'pos.till.session.open',
    'pos.till.opening.key_decimal': 'pos.till.session.open',
    'pos.till.closing.back': 'pos.till.session.close',
    'pos.till.closing.till': 'pos.till.session.close',
    'pos.till.closing.opened_by': 'pos.till.session.close',
    'pos.till.closing.opened_time': 'pos.till.session.close',
    'pos.till.closing.expected_cash': 'pos.till.session.close',
    'pos.till.closing.counted_cash_entry': 'pos.till.session.close',
    'pos.till.closing.difference': 'pos.till.session.close',
    'pos.till.closing.balance_status': 'pos.till.session.close',
    'pos.till.closing.mismatch_reason': 'pos.till.session.close',
    'pos.till.closing.notes': 'pos.till.session.close',
    'pos.till.closing.summary': 'pos.till.session.close',
    'pos.till.closing.expected_cash_summary': 'pos.till.session.close',
    'pos.till.closing.counted_cash_summary': 'pos.till.session.close',
    'pos.till.closing.difference_summary': 'pos.till.session.close',
    'pos.till.closing.status_summary': 'pos.till.session.close',
    'pos.shell.navigation.settings': 'pos.sales.dashboard.view',
    'pos.customers.management.attach_sale': 'pos.customers.management.view',
    'pos.customers.management.deactivate': 'pos.customers.management.update',
    'pos.cash_drawer.movements.cash_in': 'pos.cash_drawer.movements.create',
    'pos.cash_drawer.movements.cash_out': 'pos.cash_drawer.movements.create',
    'pos.cash_drawer.movements.cash_drop': 'pos.cash_drawer.movements.create',
    'pos.cash_drawer.open_reason.provide_change': 'pos.cash_drawer.physical.manage',
    'pos.cash_drawer.open_reason.till_check': 'pos.cash_drawer.physical.manage',
    'pos.cash_drawer.open_reason.cash_count': 'pos.cash_drawer.physical.manage',
    'pos.cash_drawer.open_reason.manager_operation': 'pos.cash_drawer.physical.manage',
    'pos.cash_drawer.open_reason.other': 'pos.cash_drawer.physical.manage',
    'pos.shell.navigation.offline_banner': 'pos.sales.dashboard.view',
    'pos.home.actions.online_orders_entry': 'commerce.online_order.orders.access',
    'pos.home.actions.returns_entry': 'pos.returns.search_sale.view',
    'pos.cash_movements.cash_in.till': 'pos.cash_drawer.movements.cash_in',
    'pos.cash_movements.cash_in.expected_cash': 'pos.cash_drawer.movements.cash_in',
    'pos.cash_movements.cash_in.available_cash': 'pos.cash_drawer.movements.cash_in',
    'pos.cash_movements.cash_in.amount_entry': 'pos.cash_drawer.movements.cash_in',
    'pos.cash_movements.cash_in.reason': 'pos.cash_drawer.movements.cash_in',
    'pos.cash_movements.cash_in.note': 'pos.cash_drawer.movements.cash_in',
    'pos.cash_movements.cash_in.manager_pin': 'pos.cash_drawer.movements.cash_in',
    'pos.cash_movements.cash_in.summary': 'pos.cash_drawer.movements.cash_in',
    'pos.cash_movements.cash_in.resulting_balance': 'pos.cash_drawer.movements.cash_in',
    'pos.cash_movements.cash_in.validation_message': 'pos.cash_drawer.movements.cash_in',
    'pos.cash_movements.cash_in.confirm': 'pos.cash_drawer.movements.cash_in',
    'pos.cash_movements.cash_in.cancel': 'pos.cash_drawer.movements.cash_in',
    'pos.cash_movements.cash_out.till': 'pos.cash_drawer.movements.cash_out',
    'pos.cash_movements.cash_out.expected_cash': 'pos.cash_drawer.movements.cash_out',
    'pos.cash_movements.cash_out.available_cash': 'pos.cash_drawer.movements.cash_out',
    'pos.cash_movements.cash_out.amount_entry': 'pos.cash_drawer.movements.cash_out',
    'pos.cash_movements.cash_out.reason': 'pos.cash_drawer.movements.cash_out',
    'pos.cash_movements.cash_out.note': 'pos.cash_drawer.movements.cash_out',
    'pos.cash_movements.cash_out.manager_pin': 'pos.cash_drawer.movements.cash_out',
    'pos.cash_movements.cash_out.summary': 'pos.cash_drawer.movements.cash_out',
    'pos.cash_movements.cash_out.resulting_balance': 'pos.cash_drawer.movements.cash_out',
    'pos.cash_movements.cash_out.validation_message': 'pos.cash_drawer.movements.cash_out',
    'pos.cash_movements.cash_out.confirm': 'pos.cash_drawer.movements.cash_out',
    'pos.cash_movements.cash_out.cancel': 'pos.cash_drawer.movements.cash_out',
    'pos.cash_movements.cash_drop.till': 'pos.cash_drawer.movements.cash_drop',
    'pos.cash_movements.cash_drop.expected_cash': 'pos.cash_drawer.movements.cash_drop',
    'pos.cash_movements.cash_drop.available_cash': 'pos.cash_drawer.movements.cash_drop',
    'pos.cash_movements.cash_drop.amount_entry': 'pos.cash_drawer.movements.cash_drop',
    'pos.cash_movements.cash_drop.reason': 'pos.cash_drawer.movements.cash_drop',
    'pos.cash_movements.cash_drop.note': 'pos.cash_drawer.movements.cash_drop',
    'pos.cash_movements.cash_drop.manager_pin': 'pos.cash_drawer.movements.cash_drop',
    'pos.cash_movements.cash_drop.summary': 'pos.cash_drawer.movements.cash_drop',
    'pos.cash_movements.cash_drop.resulting_balance': 'pos.cash_drawer.movements.cash_drop',
    'pos.cash_movements.cash_drop.validation_message': 'pos.cash_drawer.movements.cash_drop',
    'pos.cash_movements.cash_drop.confirm': 'pos.cash_drawer.movements.cash_drop',
    'pos.cash_movements.cash_drop.cancel': 'pos.cash_drawer.movements.cash_drop',
  };

  static const newCodes = <String>[
    'pos.shell.navigation.settings',
    'pos.customers.management.attach_sale',
    'pos.customers.management.deactivate',
    'pos.cash_drawer.movements.cash_in',
    'pos.cash_drawer.movements.cash_out',
    'pos.cash_drawer.movements.cash_drop',
    'pos.cash_drawer.open_reason.provide_change',
    'pos.cash_drawer.open_reason.till_check',
    'pos.cash_drawer.open_reason.cash_count',
    'pos.cash_drawer.open_reason.manager_operation',
    'pos.cash_drawer.open_reason.other',
    'pos.shell.navigation.offline_banner',
    'pos.home.actions.online_orders_entry',
    'pos.home.actions.returns_entry',
  ];

  static const splitCodes = <String>[
    'pos.shell.topbar.container',
    'pos.shell.topbar.brand',
    'pos.shell.topbar.session_status',
    'pos.shell.topbar.outlet',
    'pos.shell.topbar.till',
    'pos.shell.topbar.connectivity',
    'pos.shell.topbar.clock',
    'pos.shell.topbar.notification_bell',
    'pos.shell.bottom_nav.container',
    'pos.notifications.panel.view',
    'pos.notifications.panel.unread_count',
    'pos.notifications.messages.list',
    'pos.notifications.messages.title',
    'pos.notifications.messages.body',
    'pos.notifications.messages.timestamp',
    'pos.notifications.messages.open',
    'pos.notifications.messages.mark_read',
    'pos.notifications.messages.dismiss',
    'pos.notifications.messages.mark_all_read',
    'pos.home.profile.view',
    'pos.home.profile.avatar',
    'pos.home.profile.name',
    'pos.home.profile.role',
    'pos.home.session_summary.view',
    'pos.home.session_summary.total_sales',
    'pos.home.session_summary.transaction_count',
    'pos.home.session_summary.returns',
    'pos.home.session_summary.discounts',
    'pos.home.session_summary.net_sales',
    'pos.catalog.sections.quick_products',
    'pos.catalog.sections.popular',
    'pos.catalog.sections.frequently_sold',
    'pos.catalog.sections.offers',
    'pos.catalog.sections.sort',
    'pos.catalog.product_card.image',
    'pos.catalog.product_card.name',
    'pos.catalog.product_card.regular_price',
    'pos.catalog.product_card.sale_price',
    'pos.catalog.product_card.discount_badge',
    'pos.catalog.product_card.open_details',
    'pos.catalog.product_detail.view',
    'pos.catalog.product_detail.close',
    'pos.catalog.product_detail.image',
    'pos.catalog.product_detail.name',
    'pos.catalog.product_detail.price',
    'pos.catalog.product_detail.stock',
    'pos.catalog.product_detail.sku',
    'pos.catalog.product_detail.description',
    'pos.catalog.product_detail.variants',
    'pos.catalog.product_detail.variant_select',
    'pos.catalog.product_detail.available_qty',
    'pos.catalog.product_detail.quantity_display',
    'pos.catalog.product_detail.note_view',
    'pos.catalog.product_detail.note_entry',
    'pos.catalog.product_detail.recommendations',
    'pos.catalog.product_detail.cancel',
    'pos.held_sales.popup.view',
    'pos.held_sales.popup.reference',
    'pos.held_sales.popup.note',
    'pos.held_sales.popup.expiry',
    'pos.held_sales.list.filters',
    'pos.held_sales.list.active_count',
    'pos.held_sales.list.customer',
    'pos.held_sales.list.value',
    'pos.held_sales.list.item_count',
    'pos.held_sales.list.parked_time',
    'pos.held_sales.list.expiry_time',
    'pos.held_sales.list.items',
    'pos.held_sales.list.pagination',
    'pos.held_sales.list.summary',
    'pos.cart.summary.view',
    'pos.cart.summary.item_count',
    'pos.cart.summary.subtotal',
    'pos.cart.summary.discount',
    'pos.cart.summary.tax',
    'pos.cart.summary.total',
    'pos.cart.lines.list',
    'pos.cart.lines.name',
    'pos.cart.lines.quantity',
    'pos.cart.lines.unit_price',
    'pos.cart.lines.line_total',
    'pos.cart.lines.note',
    'pos.cart.lines.image',
    'pos.catalog.search.bar',
    'pos.catalog.search.clear',
    'pos.catalog.search.results',
    'pos.catalog.search.empty_state',
    'pos.catalog.search.scanner_hint',
    'pos.checkout.methods.cash_tile',
    'pos.checkout.methods.card_tile',
    'pos.checkout.methods.qr_tile',
    'pos.checkout.methods.split_tile',
    'pos.checkout.methods.container',
    'pos.discount.panel.view',
    'pos.discount.panel.amount_entry',
    'pos.discount.panel.reason_entry',
    'pos.discount.panel.apply_action',
    'pos.discount.panel.cancel_action',
    'pos.new_sale.chrome.header',
    'pos.new_sale.chrome.park_action',
    'pos.new_sale.chrome.customer_chip',
    'pos.new_sale.chrome.empty_cart',
    'pos.new_sale.chrome.checkout_action',
    'pos.new_sale.chrome.held_count',
    'pos.new_sale.chrome.clear_cart_action',
    'pos.checkout.summary.payment',
    'pos.checkout.summary.items',
    'pos.checkout.summary.quantity',
    'pos.checkout.summary.price',
    'pos.checkout.summary.line_total',
    'pos.checkout.customer.summary',
    'pos.checkout.summary.subtotal',
    'pos.checkout.summary.discount',
    'pos.checkout.summary.tax',
    'pos.checkout.summary.total',
    'pos.cash_payment.summary.order',
    'pos.cash_payment.line.item',
    'pos.cash_payment.line.quantity',
    'pos.cash_payment.line.price',
    'pos.cash_payment.line.item_total',
    'pos.cash_payment.summary.subtotal',
    'pos.cash_payment.summary.discount',
    'pos.cash_payment.summary.tax',
    'pos.cash_payment.summary.total_due',
    'pos.cash_payment.tender.amount_received_view',
    'pos.cash_payment.tender.amount_received_entry',
    'pos.cash_payment.tender.due_amount',
    'pos.cash_payment.tender.exact',
    'pos.cash_payment.quick_amounts.container',
    'pos.cash_payment.quick_amounts.slot_1',
    'pos.cash_payment.quick_amounts.slot_2',
    'pos.cash_payment.quick_amounts.slot_3',
    'pos.cash_payment.numpad.container',
    'pos.cash_payment.numpad.digit_0',
    'pos.cash_payment.numpad.digit_1',
    'pos.cash_payment.numpad.digit_2',
    'pos.cash_payment.numpad.digit_3',
    'pos.cash_payment.numpad.digit_4',
    'pos.cash_payment.numpad.digit_5',
    'pos.cash_payment.numpad.digit_6',
    'pos.cash_payment.numpad.digit_7',
    'pos.cash_payment.numpad.digit_8',
    'pos.cash_payment.numpad.digit_9',
    'pos.cash_payment.numpad.digit_00',
    'pos.cash_payment.numpad.decimal',
    'pos.cash_payment.controls.backspace',
    'pos.cash_payment.controls.clear',
    'pos.cash_payment.tender.change_due',
    'pos.cash_payment.completion.execute',
    'pos.sale_complete.message.success',
    'pos.sale_complete.details.receipt_number',
    'pos.sale_complete.details.payment_method',
    'pos.sale_complete.details.datetime',
    'pos.sale_complete.details.cashier',
    'pos.sale_complete.details.customer',
    'pos.sale_complete.details.cash_received',
    'pos.sale_complete.details.change_due',
    'pos.sale_complete.details.total_paid',
    'pos.receipts.details.store',
    'pos.receipts.details.receipt_number',
    'pos.receipts.details.datetime',
    'pos.receipts.details.cashier',
    'pos.receipts.details.customer',
    'pos.receipts.details.terminal',
    'pos.receipts.details.payment_method',
    'pos.receipts.details.items',
    'pos.receipts.details.item_quantity',
    'pos.receipts.details.item_value',
    'pos.receipts.details.item_rate',
    'pos.receipts.details.subtotal',
    'pos.receipts.details.discount',
    'pos.receipts.details.total',
    'pos.receipts.details.paid_amount',
    'pos.receipts.details.change_due',
    'pos.customers.list.search',
    'pos.customers.list.filters',
    'pos.customers.list.id',
    'pos.customers.list.name',
    'pos.customers.list.phone',
    'pos.customers.list.email',
    'pos.customers.list.source',
    'pos.customers.list.status',
    'pos.customers.list.order_count',
    'pos.customers.list.total_spend',
    'pos.customers.list.pagination',
    'pos.customers.details.joined_date',
    'pos.customers.details.average_order_value',
    'pos.customers.history.recent_purchases',
    'pos.customers.history.purchase_amounts',
    'pos.customers.history.purchase_history',
    'pos.cash_drawer.summary.till',
    'pos.cash_drawer.summary.status',
    'pos.cash_drawer.summary.opening_cash',
    'pos.cash_drawer.summary.cash_sales',
    'pos.cash_drawer.summary.expected_cash',
    'pos.cash_drawer.movements.list',
    'pos.cash_drawer.movements.type',
    'pos.cash_drawer.movements.date',
    'pos.cash_drawer.movements.time',
    'pos.cash_drawer.movements.cashier',
    'pos.cash_drawer.movements.amount_view',
    'pos.cash_drawer.open_popup.view',
    'pos.cash_drawer.open_popup.cancel',
    'pos.cash_drawer.open_popup.continue',
    'pos.till.opening.starting_cash_view',
    'pos.till.opening.starting_cash_entry',
    'pos.till.opening.validation_message',
    'pos.till.opening.note_view',
    'pos.till.opening.note_entry',
    'pos.till.opening.quick_amounts',
    'pos.till.opening.quick_slot_1',
    'pos.till.opening.quick_slot_2',
    'pos.till.opening.quick_slot_3',
    'pos.till.opening.numpad',
    'pos.till.opening.backspace',
    'pos.till.opening.clear',
    'pos.till.opening.confirm_message',
    'pos.till.opening.key_0',
    'pos.till.opening.key_1',
    'pos.till.opening.key_2',
    'pos.till.opening.key_3',
    'pos.till.opening.key_4',
    'pos.till.opening.key_5',
    'pos.till.opening.key_6',
    'pos.till.opening.key_7',
    'pos.till.opening.key_8',
    'pos.till.opening.key_9',
    'pos.till.opening.key_00',
    'pos.till.opening.key_decimal',
    'pos.till.closing.back',
    'pos.till.closing.till',
    'pos.till.closing.opened_by',
    'pos.till.closing.opened_time',
    'pos.till.closing.expected_cash',
    'pos.till.closing.counted_cash_entry',
    'pos.till.closing.difference',
    'pos.till.closing.balance_status',
    'pos.till.closing.mismatch_reason',
    'pos.till.closing.notes',
    'pos.till.closing.summary',
    'pos.till.closing.expected_cash_summary',
    'pos.till.closing.counted_cash_summary',
    'pos.till.closing.difference_summary',
    'pos.till.closing.status_summary',
    'pos.cash_movements.cash_in.till',
    'pos.cash_movements.cash_in.expected_cash',
    'pos.cash_movements.cash_in.available_cash',
    'pos.cash_movements.cash_in.amount_entry',
    'pos.cash_movements.cash_in.reason',
    'pos.cash_movements.cash_in.note',
    'pos.cash_movements.cash_in.manager_pin',
    'pos.cash_movements.cash_in.summary',
    'pos.cash_movements.cash_in.resulting_balance',
    'pos.cash_movements.cash_in.validation_message',
    'pos.cash_movements.cash_in.confirm',
    'pos.cash_movements.cash_in.cancel',
    'pos.cash_movements.cash_out.till',
    'pos.cash_movements.cash_out.expected_cash',
    'pos.cash_movements.cash_out.available_cash',
    'pos.cash_movements.cash_out.amount_entry',
    'pos.cash_movements.cash_out.reason',
    'pos.cash_movements.cash_out.note',
    'pos.cash_movements.cash_out.manager_pin',
    'pos.cash_movements.cash_out.summary',
    'pos.cash_movements.cash_out.resulting_balance',
    'pos.cash_movements.cash_out.validation_message',
    'pos.cash_movements.cash_out.confirm',
    'pos.cash_movements.cash_out.cancel',
    'pos.cash_movements.cash_drop.till',
    'pos.cash_movements.cash_drop.expected_cash',
    'pos.cash_movements.cash_drop.available_cash',
    'pos.cash_movements.cash_drop.amount_entry',
    'pos.cash_movements.cash_drop.reason',
    'pos.cash_movements.cash_drop.note',
    'pos.cash_movements.cash_drop.manager_pin',
    'pos.cash_movements.cash_drop.summary',
    'pos.cash_movements.cash_drop.resulting_balance',
    'pos.cash_movements.cash_drop.validation_message',
    'pos.cash_movements.cash_drop.confirm',
    'pos.cash_movements.cash_drop.cancel',
  ];

  static const documentedResolvedCodes = <String>[
    'pos.sales.held_sales.cancel',
  ];
}
