import '../../../../core/access/tenant_admin_access_codes.dart';

class TenantAdminRouteDefinition {
  const TenantAdminRouteDefinition({
    required this.path,
    required this.menuKey,
    required this.title,
    required this.featureCode,
    required this.permissionCode,
    this.subtitle,
  });

  final String path;
  final String menuKey;
  final String title;
  final String featureCode;
  final String permissionCode;
  final String? subtitle;
}

const tenantAdminRouteDefinitions = [
  TenantAdminRouteDefinition(
    path: '/tenant-admin/dashboard',
    menuKey: 'dashboard',
    title: 'Dashboard',
    featureCode: 'tenant_admin.dashboard',
    permissionCode: 'tenant.dashboard.view',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/outlets',
    menuKey: 'outlets',
    title: 'Outlets',
    featureCode: 'tenant_admin.outlets',
    permissionCode: 'tenant.outlets.view',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/outlets/add',
    menuKey: 'outlets',
    title: 'Add Outlet',
    featureCode: 'tenant_admin.outlets',
    permissionCode: 'tenant.outlets.manage',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/outlets/:id',
    menuKey: 'outlets',
    title: 'Outlet Details',
    featureCode: 'tenant_admin.outlets',
    permissionCode: 'tenant.outlets.view',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/outlets/:id/edit',
    menuKey: 'outlets',
    title: 'Edit Outlet',
    featureCode: 'tenant_admin.outlets',
    permissionCode: 'tenant.outlets.manage',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/tills',
    menuKey: 'tills',
    title: 'Tills',
    featureCode: 'tenant.tills',
    permissionCode: 'till.view',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/hardware',
    menuKey: 'hardware',
    title: 'Hardware List',
    featureCode: 'tenant.tills',
    permissionCode: 'tenant.hardware.view',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/hardware/add',
    menuKey: 'hardware',
    title: 'Add Hardware',
    featureCode: 'tenant.tills',
    permissionCode: 'tenant.hardware.manage',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/hardware/:id',
    menuKey: 'hardware',
    title: 'Hardware Details',
    featureCode: 'tenant.tills',
    permissionCode: 'tenant.hardware.view',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/hardware/:id/edit',
    menuKey: 'hardware',
    title: 'Edit Hardware',
    featureCode: 'tenant.tills',
    permissionCode: 'tenant.hardware.manage',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/tills/add',
    menuKey: 'tills',
    title: 'Add Till',
    featureCode: 'tenant.tills',
    permissionCode: 'till.create',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/tills/:id',
    menuKey: 'tills',
    title: 'Till Details',
    featureCode: 'tenant.tills',
    permissionCode: 'till.view',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/tills/:id/edit',
    menuKey: 'tills',
    title: 'Edit Till',
    featureCode: 'tenant.tills',
    permissionCode: 'till.update',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/staff',
    menuKey: 'staff',
    title: 'Users',
    featureCode: 'tenant.users',
    permissionCode: 'tenant.user.manage',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/staff/add',
    menuKey: 'staff',
    title: 'Add New User',
    featureCode: 'tenant.users',
    permissionCode: 'tenant.user.manage',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/staff/:id',
    menuKey: 'staff',
    title: 'User Details',
    featureCode: 'tenant.users',
    permissionCode: 'tenant.user.manage',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/staff/:id/edit',
    menuKey: 'staff',
    title: 'Edit User',
    featureCode: 'tenant.users',
    permissionCode: 'tenant.user.manage',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/online-store',
    menuKey: 'online-store',
    title: 'Online Store Overview',
    featureCode: TenantAdminFeatureCodes.onlineStore,
    permissionCode: TenantAdminPermissionCodes.onlineStoreView,
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/online-store/activation',
    menuKey: 'online-store',
    title: 'Activation & Access',
    featureCode: TenantAdminFeatureCodes.onlineStore,
    permissionCode: TenantAdminPermissionCodes.onlineStoreView,
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/online-store/identity',
    menuKey: 'online-store',
    title: 'Store Identity',
    featureCode: TenantAdminFeatureCodes.onlineStore,
    permissionCode: TenantAdminPermissionCodes.onlineStoreView,
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/online-store/domain',
    menuKey: 'online-store',
    title: 'Storefront URL & Domain',
    featureCode: TenantAdminFeatureCodes.onlineStore,
    permissionCode: TenantAdminPermissionCodes.onlineStoreView,
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/online-store/branding',
    menuKey: 'online-store',
    title: 'Branding & Appearance',
    featureCode: TenantAdminFeatureCodes.onlineStore,
    permissionCode: TenantAdminPermissionCodes.onlineStoreView,
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/online-store/support',
    menuKey: 'online-store',
    title: 'Contact & Support',
    featureCode: TenantAdminFeatureCodes.onlineStore,
    permissionCode: TenantAdminPermissionCodes.onlineStoreView,
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/online-store/click-collect',
    menuKey: 'online-store',
    title: 'Click & Collect Configuration',
    featureCode: TenantAdminFeatureCodes.onlineStore,
    permissionCode: TenantAdminPermissionCodes.onlineStoreView,
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/online-store/products-policies',
    menuKey: 'online-store',
    title: 'Products & Policies',
    featureCode: TenantAdminFeatureCodes.onlineStore,
    permissionCode: TenantAdminPermissionCodes.onlineStoreView,
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/online-store/review',
    menuKey: 'online-store',
    title: 'Review & Publish',
    featureCode: TenantAdminFeatureCodes.onlineStore,
    permissionCode: TenantAdminPermissionCodes.onlineStoreView,
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/roles-permissions',
    menuKey: 'roles-access',
    title: 'Roles & Permissions',
    featureCode: 'tenant.roles',
    permissionCode: 'roles.permissions.view',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/roles-permissions/:roleId',
    menuKey: 'roles-access',
    title: 'Roles & Permissions',
    featureCode: 'tenant.roles',
    permissionCode: 'roles.permissions.view',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/roles',
    menuKey: 'roles-access',
    title: 'Roles & Access',
    featureCode: 'tenant.roles',
    permissionCode: 'tenant.role.manage',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/roles/add',
    menuKey: 'roles-access',
    title: 'Add Role',
    featureCode: 'tenant.roles',
    permissionCode: 'tenant.role.manage',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/roles/:id',
    menuKey: 'roles-access',
    title: 'Role Details',
    featureCode: 'tenant.roles',
    permissionCode: 'tenant.role.manage',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/roles/:id/edit',
    menuKey: 'roles-access',
    title: 'Edit Role',
    featureCode: 'tenant.roles',
    permissionCode: 'tenant.role.manage',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/products/dashboard',
    menuKey: 'products',
    title: 'Product Dashboard',
    featureCode: 'catalog.product',
    permissionCode: 'tenant.products.dashboard.view',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/products',
    menuKey: 'products',
    title: 'Product List',
    featureCode: 'catalog.product',
    permissionCode: 'tenant.products.view',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/products/add',
    menuKey: 'products',
    title: 'Add Product',
    featureCode: 'catalog.product',
    permissionCode: 'tenant.products.create',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/products/import',
    menuKey: 'products',
    title: 'Import Products',
    featureCode: 'catalog.product',
    permissionCode: 'tenant.product.import',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/products/popular',
    menuKey: 'products',
    title: 'Popular Products',
    featureCode: 'catalog.product',
    permissionCode: 'catalog.collections.view',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/products/:id',
    menuKey: 'products',
    title: 'Product Details',
    featureCode: 'catalog.product',
    permissionCode: 'tenant.products.view',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/products/:id/edit',
    menuKey: 'products',
    title: 'Edit Product',
    featureCode: 'catalog.product',
    permissionCode: 'tenant.products.update',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/categories',
    menuKey: 'products',
    title: 'Categories',
    featureCode: 'catalog.product',
    permissionCode: 'tenant.categories.view',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/brands',
    menuKey: 'products',
    title: 'Brands',
    featureCode: 'catalog.product',
    permissionCode: 'tenant.brands.view',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/tax',
    menuKey: 'products',
    title: 'Taxes',
    featureCode: 'catalog.product',
    permissionCode: 'tenant.products.view',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/variant-templates',
    menuKey: 'products',
    title: 'Variant Templates',
    featureCode: 'catalog.product',
    permissionCode: 'tenant.variant.templates.view',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/stock',
    menuKey: 'inventory',
    title: 'Stock',
    featureCode: 'inventory.stock',
    permissionCode: 'tenant.stock.view',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/stock/dashboard',
    menuKey: 'inventory',
    title: 'Dashboard',
    featureCode: 'inventory.stock',
    permissionCode: 'tenant.stock.dashboard.view',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/stock/current',
    menuKey: 'inventory',
    title: 'Current Stock',
    featureCode: 'inventory.stock',
    permissionCode: 'tenant.stock.view',
    subtitle: 'View stock availability across accessible outlets.',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/stock/current/:variantId',
    menuKey: 'inventory',
    title: 'Product Stock Detail',
    featureCode: 'inventory.stock',
    permissionCode: 'tenant.stock.view',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/stock/in',
    menuKey: 'inventory',
    title: 'Stock In',
    featureCode: 'inventory.stock',
    permissionCode: 'tenant.stock.in',
    subtitle: 'Receive inventory into an accessible outlet.',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/stock/opening',
    menuKey: 'inventory',
    title: 'Opening Stock',
    featureCode: 'inventory.stock',
    permissionCode: 'tenant.stock.opening',
    subtitle: 'Add initial opening stock to an outlet.',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/stock/items',
    menuKey: 'inventory',
    title: 'Stock Items',
    featureCode: 'inventory.stock',
    permissionCode: 'tenant.stock.view',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/stock/adjust',
    menuKey: 'inventory',
    title: 'Adjust Stock',
    featureCode: 'inventory.stock',
    permissionCode: 'inventory.adjust',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/stock/history',
    menuKey: 'inventory',
    title: 'Stock History',
    featureCode: 'inventory.stock',
    permissionCode: 'inventory.view',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/reports',
    menuKey: 'reports',
    title: 'Reports',
    featureCode: 'reports',
    permissionCode: 'reports.view',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/reports/sales',
    menuKey: 'reports',
    title: 'Sales Report',
    featureCode: 'reports',
    permissionCode: 'reports.view',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/reports/sales/:orderId',
    menuKey: 'reports',
    title: 'Transaction Detail',
    featureCode: 'reports',
    permissionCode: 'reports.view',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/reports/stock',
    menuKey: 'reports',
    title: 'Stock Report',
    featureCode: 'reports',
    permissionCode: 'reports.view',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/reports/outlets',
    menuKey: 'reports',
    title: 'Outlet Report',
    featureCode: 'reports',
    permissionCode: 'reports.view',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/billing',
    menuKey: 'billing',
    title: 'Billing Summary',
    featureCode: 'subscription.billing',
    permissionCode: 'tenant.billing.view',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/settings',
    menuKey: 'settings',
    title: 'Settings',
    featureCode: 'tenant.settings',
    permissionCode: 'tenant.settings.manage',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/activity',
    menuKey: 'activity',
    title: 'Activity',
    featureCode: 'tenant.activity',
    permissionCode: 'tenant.activity.view',
  ),
];
