class TenantAdminRouteDefinition {
  const TenantAdminRouteDefinition({
    required this.path,
    required this.menuKey,
    required this.title,
    required this.featureCode,
    required this.permissionCode,
    this.subtitle,
  });

  final String path;
  final String menuKey;
  final String title;
  final String featureCode;
  final String permissionCode;
  final String? subtitle;
}

const tenantAdminRouteDefinitions = [
  TenantAdminRouteDefinition(
    path: '/tenant-admin/dashboard',
    menuKey: 'dashboard',
    title: 'Dashboard',
    featureCode: 'tenant_admin.dashboard',
    permissionCode: 'dashboard.view',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/outlets',
    menuKey: 'outlets',
    title: 'Outlets',
    featureCode: 'tenant_admin.outlets',
    permissionCode: 'outlets.view',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/outlets/add',
    menuKey: 'outlets',
    title: 'Add Outlet',
    featureCode: 'tenant_admin.outlets',
    permissionCode: 'outlets.create',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/outlets/:id',
    menuKey: 'outlets',
    title: 'Outlet Details',
    featureCode: 'tenant_admin.outlets',
    permissionCode: 'outlets.view',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/outlets/:id/edit',
    menuKey: 'outlets',
    title: 'Edit Outlet',
    featureCode: 'tenant_admin.outlets',
    permissionCode: 'outlets.update',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/tills',
    menuKey: 'tills',
    title: 'Tills',
    featureCode: 'tenant.tills',
    permissionCode: 'tenant.till.manage',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/tills/add',
    menuKey: 'tills',
    title: 'Add Till',
    featureCode: 'tenant.tills',
    permissionCode: 'tenant.till.manage',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/tills/:id',
    menuKey: 'tills',
    title: 'Till Details',
    featureCode: 'tenant.tills',
    permissionCode: 'tenant.till.manage',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/tills/:id/edit',
    menuKey: 'tills',
    title: 'Edit Till',
    featureCode: 'tenant.tills',
    permissionCode: 'tenant.till.manage',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/staff',
    menuKey: 'staff',
    title: 'Staff',
    featureCode: 'tenant.users',
    permissionCode: 'tenant.user.manage',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/staff/add',
    menuKey: 'staff',
    title: 'Add Staff',
    featureCode: 'tenant.users',
    permissionCode: 'tenant.user.manage',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/staff/:id',
    menuKey: 'staff',
    title: 'Staff Details',
    featureCode: 'tenant.users',
    permissionCode: 'tenant.user.manage',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/staff/:id/edit',
    menuKey: 'staff',
    title: 'Edit Staff',
    featureCode: 'tenant.users',
    permissionCode: 'tenant.user.manage',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/roles',
    menuKey: 'roles-access',
    title: 'Roles & Access',
    featureCode: 'tenant.roles',
    permissionCode: 'tenant.role.manage',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/roles/add',
    menuKey: 'roles-access',
    title: 'Add Role',
    featureCode: 'tenant.roles',
    permissionCode: 'tenant.role.manage',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/roles/:id',
    menuKey: 'roles-access',
    title: 'Role Details',
    featureCode: 'tenant.roles',
    permissionCode: 'tenant.role.manage',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/roles/:id/edit',
    menuKey: 'roles-access',
    title: 'Edit Role',
    featureCode: 'tenant.roles',
    permissionCode: 'tenant.role.manage',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/products',
    menuKey: 'products',
    title: 'Products',
    featureCode: 'catalog.product',
    permissionCode: 'catalog.product.view',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/products/add',
    menuKey: 'products',
    title: 'Add Product',
    featureCode: 'catalog.product',
    permissionCode: 'catalog.product.create',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/products/import',
    menuKey: 'products',
    title: 'Import Products',
    featureCode: 'catalog.product',
    permissionCode: 'tenant.product.import',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/products/:id',
    menuKey: 'products',
    title: 'Product Details',
    featureCode: 'catalog.product',
    permissionCode: 'catalog.product.view',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/products/:id/edit',
    menuKey: 'products',
    title: 'Edit Product',
    featureCode: 'catalog.product',
    permissionCode: 'catalog.product.update',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/stock',
    menuKey: 'stock',
    title: 'Stock',
    featureCode: 'inventory.stock',
    permissionCode: 'inventory.view',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/stock/items',
    menuKey: 'stock',
    title: 'Stock Items',
    featureCode: 'inventory.stock',
    permissionCode: 'inventory.view',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/stock/adjust',
    menuKey: 'stock',
    title: 'Adjust Stock',
    featureCode: 'inventory.stock',
    permissionCode: 'inventory.adjust',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/stock/history',
    menuKey: 'stock',
    title: 'Stock History',
    featureCode: 'inventory.stock',
    permissionCode: 'inventory.view',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/reports',
    menuKey: 'reports',
    title: 'Reports',
    featureCode: 'reports',
    permissionCode: 'reports.view',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/reports/sales',
    menuKey: 'reports',
    title: 'Sales Report',
    featureCode: 'reports',
    permissionCode: 'reports.view',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/reports/stock',
    menuKey: 'reports',
    title: 'Stock Report',
    featureCode: 'reports',
    permissionCode: 'reports.view',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/reports/outlets',
    menuKey: 'reports',
    title: 'Outlet Report',
    featureCode: 'reports',
    permissionCode: 'reports.view',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/billing',
    menuKey: 'billing',
    title: 'Billing Summary',
    featureCode: 'subscription.billing',
    permissionCode: 'tenant.billing.view',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/settings',
    menuKey: 'settings',
    title: 'Settings',
    featureCode: 'tenant.settings',
    permissionCode: 'tenant.settings.manage',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/activity',
    menuKey: 'activity',
    title: 'Activity',
    featureCode: 'tenant.activity',
    permissionCode: 'tenant.activity.view',
  ),
];
