class TenantAdminRouteDefinition {
  const TenantAdminRouteDefinition({
    required this.path,
    required this.menuKey,
    required this.title,
    required this.featureCode,
    required this.permissionCode,
    this.subtitle,
  });

  final String path;
  final String menuKey;
  final String title;
  final String featureCode;
  final String permissionCode;
  final String? subtitle;
}

const tenantAdminRouteDefinitions = [
  TenantAdminRouteDefinition(
    path: '/tenant-admin/dashboard',
    menuKey: 'dashboard',
    title: 'Dashboard',
    featureCode: 'tenant_admin.dashboard',
    permissionCode: 'tenant.dashboard.view',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/outlets',
    menuKey: 'outlets',
    title: 'Outlets',
    featureCode: 'tenant_admin.outlets',
    permissionCode: 'outlet.view',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/outlets/add',
    menuKey: 'outlets',
    title: 'Add Outlet',
    featureCode: 'tenant_admin.outlets',
    permissionCode: 'outlet.create',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/outlets/:id',
    menuKey: 'outlets',
    title: 'Outlet Details',
    featureCode: 'tenant_admin.outlets',
    permissionCode: 'outlet.detail.view',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/outlets/:id/edit',
    menuKey: 'outlets',
    title: 'Edit Outlet',
    featureCode: 'tenant_admin.outlets',
    permissionCode: 'outlet.update',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/tills',
    menuKey: 'tills',
    title: 'Tills',
    featureCode: 'tenant.tills',
    permissionCode: 'till.view',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/tills/add',
    menuKey: 'tills',
    title: 'Add Till',
    featureCode: 'tenant.tills',
    permissionCode: 'till.create',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/tills/:id',
    menuKey: 'tills',
    title: 'Till Details',
    featureCode: 'tenant.tills',
    permissionCode: 'till.view',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/tills/:id/edit',
    menuKey: 'tills',
    title: 'Edit Till',
    featureCode: 'tenant.tills',
    permissionCode: 'till.update',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/staff',
    menuKey: 'staff',
    title: 'Users',
    featureCode: 'tenant.users',
    permissionCode: 'tenant.user.manage',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/staff/add',
    menuKey: 'staff',
    title: 'Add New User',
    featureCode: 'tenant.users',
    permissionCode: 'tenant.user.manage',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/staff/:id',
    menuKey: 'staff',
    title: 'User Details',
    featureCode: 'tenant.users',
    permissionCode: 'tenant.user.manage',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/staff/:id/edit',
    menuKey: 'staff',
    title: 'Edit User',
    featureCode: 'tenant.users',
    permissionCode: 'tenant.user.manage',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/roles-permissions',
    menuKey: 'roles-access',
    title: 'Roles & Permissions',
    featureCode: 'tenant.roles',
    permissionCode: 'roles.permissions.view',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/roles-permissions/:roleId',
    menuKey: 'roles-access',
    title: 'Roles & Permissions',
    featureCode: 'tenant.roles',
    permissionCode: 'roles.permissions.view',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/roles',
    menuKey: 'roles-access',
    title: 'Roles & Access',
    featureCode: 'tenant.roles',
    permissionCode: 'tenant.role.manage',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/roles/add',
    menuKey: 'roles-access',
    title: 'Add Role',
    featureCode: 'tenant.roles',
    permissionCode: 'tenant.role.manage',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/roles/:id',
    menuKey: 'roles-access',
    title: 'Role Details',
    featureCode: 'tenant.roles',
    permissionCode: 'tenant.role.manage',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/roles/:id/edit',
    menuKey: 'roles-access',
    title: 'Edit Role',
    featureCode: 'tenant.roles',
    permissionCode: 'tenant.role.manage',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/products/dashboard',
    menuKey: 'products',
    title: 'Product Dashboard',
    featureCode: 'catalog.product',
    permissionCode: 'tenant.products.dashboard.view',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/products',
    menuKey: 'products',
    title: 'Product List',
    featureCode: 'catalog.product',
    permissionCode: 'tenant.products.view',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/products/add',
    menuKey: 'products',
    title: 'Add Product',
    featureCode: 'catalog.product',
    permissionCode: 'tenant.products.create',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/products/import',
    menuKey: 'products',
    title: 'Import Products',
    featureCode: 'catalog.product',
    permissionCode: 'tenant.product.import',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/products/:id',
    menuKey: 'products',
    title: 'Product Details',
    featureCode: 'catalog.product',
    permissionCode: 'tenant.products.view',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/products/:id/edit',
    menuKey: 'products',
    title: 'Edit Product',
    featureCode: 'catalog.product',
    permissionCode: 'tenant.products.update',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/categories',
    menuKey: 'products',
    title: 'Categories',
    featureCode: 'catalog.product',
    permissionCode: 'tenant.categories.view',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/brands',
    menuKey: 'products',
    title: 'Brands',
    featureCode: 'catalog.product',
    permissionCode: 'tenant.brands.view',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/variant-templates',
    menuKey: 'products',
    title: 'Variant Templates',
    featureCode: 'catalog.product',
    permissionCode: 'tenant.variant.templates.view',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/stock',
    menuKey: 'stock',
    title: 'Stock',
    featureCode: 'inventory.stock',
    permissionCode: 'tenant.stock.view',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/stock/current',
    menuKey: 'stock',
    title: 'Current Stock',
    featureCode: 'inventory.stock',
    permissionCode: 'tenant.stock.view',
    subtitle: 'View stock availability across accessible outlets.',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/stock/in',
    menuKey: 'stock',
    title: 'Stock In',
    featureCode: 'inventory.stock',
    permissionCode: 'tenant.stock.in',
    subtitle: 'Receive inventory into an accessible outlet.',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/stock/items',
    menuKey: 'stock',
    title: 'Stock Items',
    featureCode: 'inventory.stock',
    permissionCode: 'tenant.stock.view',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/stock/adjust',
    menuKey: 'stock',
    title: 'Adjust Stock',
    featureCode: 'inventory.stock',
    permissionCode: 'inventory.adjust',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/stock/history',
    menuKey: 'stock',
    title: 'Stock History',
    featureCode: 'inventory.stock',
    permissionCode: 'inventory.view',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/reports',
    menuKey: 'reports',
    title: 'Reports',
    featureCode: 'reports',
    permissionCode: 'reports.view',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/reports/sales',
    menuKey: 'reports',
    title: 'Sales Report',
    featureCode: 'reports',
    permissionCode: 'reports.view',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/reports/stock',
    menuKey: 'reports',
    title: 'Stock Report',
    featureCode: 'reports',
    permissionCode: 'reports.view',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/reports/outlets',
    menuKey: 'reports',
    title: 'Outlet Report',
    featureCode: 'reports',
    permissionCode: 'reports.view',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/billing',
    menuKey: 'billing',
    title: 'Billing Summary',
    featureCode: 'subscription.billing',
    permissionCode: 'tenant.billing.view',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/settings',
    menuKey: 'settings',
    title: 'Settings',
    featureCode: 'tenant.settings',
    permissionCode: 'tenant.settings.manage',
  ),
  TenantAdminRouteDefinition(
    path: '/tenant-admin/activity',
    menuKey: 'activity',
    title: 'Activity',
    featureCode: 'tenant.activity',
    permissionCode: 'tenant.activity.view',
  ),
];
